cde-core/resource/resources/custom/amd-components/popup/ExportPopupComponent.js
- Components can't be accessed globally because they are declared within the scope of the require callback function.
=> [CDE-376] - Refactor custom components to use require

cde-core/resource/resources/custom/components/AjaxRequestComponent/AjaxRequestComponent.js, cde-pentaho5/solution/pentaho-cdf-dd/tests/ajaxRequest.cda, cde-pentaho5/solution/pentaho-cdf-dd/tests/ajaxRequest.cdfde, cde-pentaho5/solution/pentaho-cdf-dd/tests/ajaxRequest.wcdf
- Using Dashboards.fireChange instead of Dashboards.setParameter to trigger listeners after updating the parameter that holds the result value
- Updated sample
=> [CDE-437] - AjaxRequestComponent fails to trigger components that are listening to the updated parameter

cde-core/resource/resources/custom/components/Duplicate/duplicate.js, cde-pentaho5/solution/pentaho-cdf-dd/tests/DuplicateComponent/duplicateComponent.cdfde, cde-pentaho5/solution/pentaho-cdf-dd/tests/DuplicateComponent/duplicateComponent.wcdf, cde-pentaho5/solution/pentaho-cdf-dd/tests/DuplicateComponent/index.locale, cde-pentaho5/solution/pentaho-cdf-dd/tests/DuplicateComponent/index.properties, cde-pentaho5/solution/pentaho-cdf-dd/tests/DuplicateComponent/index.xml
=> [CDE-439] - DuplicateComponent fails when duplicating the HTML object for the new duplicated component

cde-core/resource/js/cdf-dd.js, cde-core/src/pt/webdetails/cdf/dd/model/inst/writer/cggrunjs/CggRunJsComponentWriteContext.java, cde-core/src/pt/webdetails/cdf/dd/model/inst/writer/cggrunjs/CggRunJsDashboardWriteContext.java, cde-core/src/pt/webdetails/cdf/dd/model/inst/writer/cggrunjs/CggRunJsDashboardWriter.java, cde-core/src/pt/webdetails/cdf/dd/model/inst/writer/cggrunjs/CggRunJsDataSourceComponentWriter.java, cde-core/src/pt/webdetails/cdf/dd/model/inst/writer/cggrunjs/CggRunJsGenericComponentWriter.java, cde-core/src/pt/webdetails/cdf/dd/model/inst/writer/cggrunjs/CggRunJsThingWriterFactory.java
The changes were made on:
- CggRunJsThingWriterFactory.java
- cdf-dd.js
The rest is just license updates and code style review
=> [CDE-286]: CGG Dial Componente - Bug while trying to see using URL

cde-core/resource/js/cdf-dd-tablemanager.js, cde-core/resource/resources/custom/components/popup/component.xml, cde-core/test-js/cdf-dd-aceWrapper-spec.js, cde-core/test-js/cdf-dd-base-spec.js, cde-core/test-js/cdf-dd-components-generic-spec.js, cde-core/test-js/cdf-dd-components-spec.js, cde-core/test-js/cdf-dd-datasources-editor-spec.js, cde-core/test-js/cdf-dd-datasources-spec.js, cde-core/test-js/cdf-dd-spec.js, cde-core/test-js/cdf-dd-tablemanager-spec.js, cde-core/test-js/cdf-dd-tableoperations-spec.js
=> [CDE-424]: ExportPopupComponent - alternative to shift+g and licenses update

cde-core/src/pt/webdetails/cdf/dd/CdeEngine.java, cde-core/src/pt/webdetails/cdf/dd/extapi/ICdeApiPathProvider.java, cde-core/src/pt/webdetails/cdf/dd/extapi/IFileHandler.java, cde-pentaho-base/src/pt/webdetails/cdf/dd/cdf/CdfStyles.java, cde-pentaho-base/src/pt/webdetails/cdf/dd/cdf/CdfTemplates.java, cde-pentaho/src/pt/webdetails/cdf/dd/CdeLifeCycleListener.java, cde-pentaho/src/pt/webdetails/cdf/dd/DashboardDesignerContentGenerator.java, cde-pentaho/src/pt/webdetails/cdf/dd/DashboardDesignerFileInfoGenerator.java, cde-pentaho/src/pt/webdetails/cdf/dd/InterPluginBroker.java, cde-pentaho/src/pt/webdetails/cdf/dd/PentahoCdeEnvironment.java, cde-pentaho/src/pt/webdetails/cdf/dd/extapi/LegacyFileHandler.java, cde-pentaho5/src/pt/webdetails/cdf/dd/api/DatasourcesApi.java, cde-pentaho5/src/pt/webdetails/cdf/dd/api/EditorApi.java, cde-pentaho5/src/pt/webdetails/cdf/dd/api/PluginsApi.java, cde-pentaho5/src/pt/webdetails/cdf/dd/api/ResourcesApi.java, cde-pentaho5/src/pt/webdetails/cdf/dd/api/SyncronizerApi.java, cde-pentaho5/src/pt/webdetails/cdf/dd/api/VersionApi.java, cde-pentaho5/src/pt/webdetails/cdf/dd/extapi/CdeApiPathProvider.java, cde-pentaho5/src/pt/webdetails/cdf/dd/extapi/FileHandler.java, cde-pentaho5/test-src/pt/webdetails/cdf/dd/testUtils/MockResourceLoader.java
=> Cde 442 The CDE folder that gets created under public should be hidden

cde-core/resource/resources/cdf-dd.html, cde-core/resource/resources/styles/Clean.html, cde-core/resource/resources/styles/WDDocs.html
=> [CDF-458]: Build capability to format numbers into CDF

cde-core/resource/resources/custom/components/ViewManager/dashboardViews.js, cde-core/resource/resources/custom/components/ViewManager/viewManager-implementation.js, cde-pentaho/resource/js/viewsHelper.js, cde-pentaho/resource/resources/custom/components/ViewManager/component.xml, cde-pentaho/resource/resources/custom/components/ViewManager/dashboardViews.js, cde-pentaho/resource/resources/custom/components/ViewManager/viewManager-implementation.js, cde-pentaho/resource/resources/custom/components/ViewManager/views.css, cde-pentaho/solution/pentaho-cdf-dd/tests/ViewManager/index.xml, cde-pentaho/solution/pentaho-cdf-dd/tests/ViewManager/viewManager.cdfde, cde-pentaho/solution/pentaho-cdf-dd/tests/ViewManager/viewManager.wcdf, cde-pentaho5/resource/js/viewsHelper.js, cde-pentaho5/solution/pentaho-cdf-dd/tests/ViewManager/index.locale, cde-pentaho5/solution/pentaho-cdf-dd/tests/ViewManager/index.xml, cde-pentaho5/solution/pentaho-cdf-dd/tests/ViewManager/viewManager.cdfde, cde-pentaho5/solution/pentaho-cdf-dd/tests/ViewManager/viewManager.wcdf
- Reviewed ViewManager custom component's Backbone implementation
- Moved previous ViewManager custom component implementation for 4.x into cde-pentaho resources folder
- Added samples for 4.x and 5.x
=> [CDE-447] - ViewManager custom component fails to save/load views

cde-core/resource/css/scrollable-navig.css, cde-pentaho/resource/js/cdf-dd-base.js, cde-pentaho5/resource/js/cdf-dd-base.js
=> [CDE-422]: fixed warning popup on firefox

cde-core/src/pt/webdetails/cdf/dd/render/layout/ResourceFileRender.java
=> [CDE-374] - Added missing render method for FileResources.

cde-core/src/pt/webdetails/cdf/dd/model/inst/writer/cdfrunjs/dashboard/CdfRunRequireJsDashboardWriter.java
- avoid executing 'require.config(requireCfg);' when no extra configuration exists
=> [CDE-374] - Review the js resource inclusion

cde-core/resource/js/cdf-dd-datasources-generic.js, cde-core/resource/js/cdf-dd-tablemanager.js, cde-core/src/pt/webdetails/cdf/dd/model/inst/writer/cdfrunjs/properties/CdfRunJsDataSourcePropertyBindingWriter.java, cde-core/test-src/pt/webdetails/cdf/dd/model/inst/writer/cdfrunjs/properties/CdfRunJsDataSourcePropertyBindingWriterTest.java
Did some refactoring to the functions that deal with file paths
=> [CDE-454] CDA datasources are created referencing the cda file's complete path

cde-core/config/karma.ci.conf.js, cde-core/config/karma.conf.js, cde-core/resource/css/master.css, cde-core/resource/editor.includes.properties, cde-core/resource/js/cdf-dd-commands.js, cde-core/resource/js/cdf-dd-palletemanager.js, cde-core/resource/js/cdf-dd-tablemanager.js, cde-core/resource/js/cdf-dd-tableoperations.js, cde-core/resource/js/cdf-dd.js, cde-core/resource/resources/cdf-dd.html, cde-core/src/pt/webdetails/cdf/dd/editor/DashboardEditor.java, cde-core/test-js/cdf-dd-commands-spec.js, cde-pentaho/resource/js/cdf-dd-base.js, cde-pentaho5/resource/js/cdf-dd-base.js
=> [CDE-409]: Save div doesn't appear when page is scrolled down

cde-core/src/pt/webdetails/cdf/dd/model/inst/writer/cggrunjs/CggRunJsGenericComponentWriter.java, cde-core/src/pt/webdetails/cdf/dd/model/inst/writer/cggrunjs/CggRunJsThingWriterFactory.java, cde-core/test-src/pt/webdetails/cdf/dd/model/inst/writer/cdfrunjs/CggRunJsThingWriterFactoryTest.java
=> [CDE-456]: Error saving dashboards with CggDialComponent

cde-core/resource/js/cdf-dd-components-charts.js, cde-core/resource/js/cdf-dd-components-generic.js, cde-core/resource/js/cdf-dd-components-others.js, cde-core/resource/js/cdf-dd-components-selectors.js, cde-core/resource/js/cdf-dd-datasources.js, cde-core/resource/js/cdf-dd-tablemanager.js, cde-core/resource/js/cdf-dd.js, cde-core/resource/resources/cdf-dd.html
=> [CDE-464] Review all SelectRenderers autocomplete data, to remove empty suggestions

cde-core/resource/js/cdf-dd-components-generic.js, cde-core/resource/resources/base/properties/Language.xml
=> [CDE-465] Several issues with the scripting datasources

cde-core/resource/resources/custom/components/ViewManager/dashboardViews.js
=> [CDE-460] Olap selector component's template variable is overriden by another component

cde-pentaho/solution/pentaho-cdf-dd/tests/addIns.cdfde, cde-pentaho5/solution/pentaho-cdf-dd/tests/addIns.cdfde
=> [CDE-472] On Addin Reference sample the Hyperlink section has innacurate information

cde-core/resource/js/cdf-dd-layout-mobile.js, cde-core/resource/js/cdf-dd-layout.js, cde-core/resource/js/cdf-dd-palletemanager.js, cde-core/resource/js/cdf-dd-tablemanager.js, cde-core/resource/js/cdf-dd-tableoperations.js, cde-core/resource/js/cdf-dd.js
=> [CDE-467] scroll keys also scroll page when there's a scroller

cde-pentaho5/solution/pentaho-cdf-dd-require/tests/maps.cdfde
- fixed 'Map Component Reference' sample by adding the value of the 'Name' property for the JS resource run_prettify.js
=> [CDE-371] - Add support for Require js in CDE

cde-core/resource/resources/custom/components/NewMapComponent/NewMapComponent.js
=> [CDE-319] ColorMap for shape in NewMapComponent

cde-core/resource/js/cdf-dd-tablemanager.js, cde-core/src/pt/webdetails/cdf/dd/DashboardManager.java, cde-core/src/pt/webdetails/cdf/dd/model/inst/writer/cdfrunjs/dashboard/CdfRunJsDashboardWriteContext.java, cde-core/src/pt/webdetails/cdf/dd/model/inst/writer/cdfrunjs/dashboard/amd/CdfRunJsDashboardWriter.java, cde-core/src/pt/webdetails/cdf/dd/model/inst/writer/cdfrunjs/dashboard/legacy/CdfRunJsDashboardWriter.java, cde-core/test-src/pt/webdetails/cdf/dd/model/inst/writer/cdfrunjs/components/amd/CdfRunJsGenericComponentWriterTest.java, cde-core/test-src/pt/webdetails/cdf/dd/model/inst/writer/cdfrunjs/components/amd/CdfRunJsParameterComponentWriterTest.java, cde-core/test-src/pt/webdetails/cdf/dd/model/inst/writer/cdfrunjs/dashboard/amd/CdfRunJsDashboardWriterTest.java, cde-pentaho5/solution/pentaho-cdf-dd/pentaho-cdf-dd-require/dashboard/template.html, cde-pentaho5/src/pt/webdetails/cdf/dd/api/RenderApi.java
- Using the same mechanism as widgets to produce unique component/parameter/html ids
- Removed some redundant source code
- Updated unit tests accordingly
- Updated the "dashboard module" sample to require the same dashboard twice, without conflicts in id's using the "alias" URL parameter
=> [CDE-380] - Investigate how can we request a dashboard using require

cde-core/config/karma.ci.conf.js, cde-core/config/karma.conf.js, cde-core/resource/js/cdf-dd-layout.js, cde-core/test-js/cdf-dd-layout-spec.js
=> [CDE-478] When adding resource popup doesn't close

cde-core/resource/resources/custom/components/NewMapComponent/NewMapComponent.js
=> [CDE-319] minor fix in NewMapComponent

cde-core/resource/css/master.css, cde-core/resource/css/untitled.css, cde-core/resource/js/cdf-dd.js, cde-core/resource/resources/cdf-dd.html, cde-pentaho/resource/js/cdf-dd-base.js, cde-pentaho5/resource/js/cdf-dd-base.js
=> [CDE-356] Trying to create a new dashboard from a saved dashboard fails server-side error

cde-pentaho5/src/pt/webdetails/cdf/dd/InterPluginBroker.java, cde-pentaho5/src/pt/webdetails/cdf/dd/api/RenderApi.java
=> [CDF-501] Dashboards.context.params is not receiving the parameter defined in the URL

build-res/subfloor-js.xml, cde-core/build.xml, cde-core/resource/js/cde-core-require-js-cfg.js, cde-pentaho5/build-res/cdf.build.js, cde-pentaho5/build.xml, cde-pentaho5/package.json, cde-pentaho5/resource/js/cde-pentaho-require-js-cfg.js
- added minification for AMD custom components
- simplified ant target test-js
=> [CDE-378] - Review build process with minification

cde-core/resource/js/cdf-dd-components-generic.js, cde-core/resource/js/cdf-dd-palletemanager.js, cde-core/resource/js/cdf-dd-prompt-wizard.js, cde-core/test-js/cdf-dd-datasources-editor-spec.js
=> [CDA-119] Scriptable JavaScript Data Source

cde-core/resource/resources/base/components/selectors/RadioRender.xml, cde-core/resource/resources/base/properties/DefaultIfEmpty.xml
=> [CDE-355] Radio Button Component --- Option to Default not visible

cde-core/resource/css/master.css, cde-core/resource/css/scrollable-navig.css
=> [CDE-459] Apply Template window - issue with slider arrows

cde-core/resource/resources/custom/components/NewMapComponent/NewMapComponent.js, cde-core/resource/resources/custom/components/NewMapComponent/mapengine-google.js, cde-core/resource/resources/custom/components/NewMapComponent/mapengine-openlayers.js, cde-pentaho/solution/pentaho-cdf-dd/tests/maps.cdfde, cde-pentaho5/solution/pentaho-cdf-dd/tests/maps.cdfde
update samples to reflect the changes made to NewMapComponent
=> [CDE-268] Unable to select a polygon created using an .kml file

cde-core/resource/css/master.css, cde-core/resource/js/cdf-dd-components-generic.js, cde-core/resource/js/cdf-dd-tablemanager.js, cde-core/resource/resources/custom/amd-components/popup/PopupComponent.css, cde-core/resource/resources/custom/components/popup/popup.css, cde-core/test-js/legacy/cdf-dd-components-generic-spec.js, cde-core/test-js/legacy/cdf-dd-tablemanager-spec.js
[CDE-507] - Table Component Column Type: Add hidden
[CDE-514] - As a developers, when I'm using the ExportPopupComponent, I don't get all the options on the 'Data/Chart Component to Export' property
=> [CDE-507][CDE-514]

cde-core/resource/js/cdf-dd-palletemanager.js, cde-core/resource/js/cdf-dd-tablemanager.js, cde-core/resource/js/cdf-dd.js, cde-core/test-js/legacy/cdf-dd-tablemanager-spec.js
[CDE-509] When using up and down arrows to navigate chart's advanced properties view doesn't scroll along with selected property
[CDE-510] When using up and down arrows to navigate Components Panel it also scrolls the accordion
=> [CDE-509][CDE-510]

cde-core/resource/js/cdf-dd-tablemanager.js, cde-core/resource/resources/custom/amd-components/popup/ExportPopupComponent.js, cde-core/resource/resources/custom/components/popup/component.xml, cde-core/resource/resources/custom/components/popup/popup.js, cde-core/test-js/components/ExportPopupComponent-spec.js, cde-core/test-js/legacy/cdf-dd-tablemanager-spec.js
[CDE-430] ExportPopupComponent - pressing down show list available options
[CDF-502] Bug PopupExportComponent with array parameters
=> [CDE-430][CDF-502]

cde-pentaho5/build.xml
=> [CLEANUP] - Remove sonar old targets

cde-core/resource/js/cdf-dd-tablemanager.js, cde-core/resource/resources/custom/amd-components/popup/ExportPopupComponent.js, cde-core/resource/resources/custom/components/popup/component.xml, cde-core/resource/resources/custom/components/popup/popup.js, cde-core/test-js/components/ExportPopupComponent-spec.js, cde-core/test-js/legacy/cdf-dd-tablemanager-spec.js, cde-pentaho5/build.xml
=> Future develop

cde-pentaho/solution/pentaho-cdf-dd/tests/ccc_bullet.cda, cde-pentaho/solution/pentaho-cdf-dd/tests/ccc_bullet.cdfde, cde-pentaho5/solution/pentaho-cdf-dd/tests/ccc_bullet.cda, cde-pentaho5/solution/pentaho-cdf-dd/tests/ccc_bullet.cdfde, cde-pentaho5/solution/pentaho-cdf-dd/tests/ccc_bullet.wcdf
=> [CDE-520] Bullet Chart doesn't render all charts

cde-core/resource/resources/custom/amd-components/OlapSelector/OlapSelectorComponent.css, cde-core/resource/resources/custom/amd-components/OlapSelector/OlapSelectorModel.js, cde-core/resource/resources/custom/amd-components/OlapSelector/OlapSelectorView.js, cde-core/resource/resources/custom/components/OlapSelector/OlapSelector.css, cde-core/resource/resources/custom/components/OlapSelector/OlapSelector.js
=> [CDE-519] Review Olap Selector sample

cde-core/resource/css/stringlist.css, cde-core/resource/js/cdf-dd-components-generic.js, cde-core/resource/js/cdf-dd-tablemanager.js
=> [CDE-450] TableComponent: Drag-and-drop on Column Headers/Types/Formats/Widths popups

cde-pentaho5/solution/pentaho-cdf-dd/pentaho-cdf-dd-require/tests/ccc_bullet.cda, cde-pentaho5/solution/pentaho-cdf-dd/pentaho-cdf-dd-require/tests/ccc_bullet.cdfde
=> [CDE-520] update Bullet Chart require-js sample

cde-core/resource/js/cdf-dd.js
- don't show confirmation box if dirtyStatus isn't set or if no commands were executed
=> [CDE-287] - Confirmation box without any previous changes

cde-core/resource/js/cdf-dd.js
- Validate if the name is not empty, is not equal to ".wcdf" and doesn't match RESERVED_CHARS_REGEX_PATTERN (webcontext.js) including the colon char
=> [CDE-397] - It is possible to save a dashboard with no name

cde-core/resource/resources/custom/amd-components/popup/ExportPopupComponent.js, cde-core/resource/resources/custom/components/popup/popup.js
- fixed bug when exporting PNG and SVG charts, error reading the file extension string
=> [CDE-538] - ExportPopupComponent fails to export PNG and SVG charts

.gitignore, cde-core/resource/resources/base/components/others/VisualizationAPIRender.xml, cde-pentaho5/solution/pentaho-cdf-dd/tests/VisualizationAPIreference.cdfde
This commit should be accepted along with those in the CDF PR: https://github.com/webdetails/cdf/pull/472.
@pamval please review.
=> [BACKLOG-2540] - AMD Conversion - Update to use new VizAPI

cde-core/src/pt/webdetails/cdf/dd/model/inst/writer/cdfrunjs/dashboard/amd/CdfRunJsDashboardWriter.java, cde-core/test-src/pt/webdetails/cdf/dd/model/inst/writer/cdfrunjs/dashboard/amd/CdfRunJsDashboardWriterTest.java
- added JS and CSS inline and external resources to the required dashboard class
=> [CDE-542] - When requiring a dashboard, using the getDashboard endpoint, inline resources and external resources are not being included.

cde-core/resource/lang/messages_en.properties
=> BACKLOG-3306 - Checkin 5.4 Localization files from Acclaro (2nd drop)

cde-core/resource/resources/custom/amd-components/popup/ExportPopupComponent.css, cde-core/resource/resources/custom/components/popup/ExportPopupComponent.css
=> [CDF-546] Fix css rules on export popup component

cde-pentaho5/ivy.xml, cde-pentaho5/resource/plugin.spring.xml, cde-pentaho5/src/pt/webdetails/cdf/dd/CdeApi.java, cde-pentaho5/src/pt/webdetails/cdf/dd/embed/EmbeddedHeadersGenerator.java, cde-pentaho5/test-src/pt/webdetails/cdf/dd/embed/EmbeddedHeadersGeneratorForTests.java, cde-pentaho5/test-src/pt/webdetails/cdf/dd/embed/EmbeddedHeadersGeneratorTest.java
- added /cde-embed.js endpoint
- added unit tests
=> [CDE-550] - Missing requireJS config for embedding CDE dashboards

cde-pentaho5/solution/pentaho-cdf-dd/pentaho-cdf-dd-require/embeddedSample/dashboard/sample.cdfde
@pamval @jvelasques @afrjorge please review
=> [CDF-558] - Updated resource link to avoid javascript error

cde-core/resource/resources/base/components/others/QueryRender.xml, cde-core/resource/resources/base/properties/AsynchronousMode.xml
=> [CDE-479] Include the 'unmanagedQueryComponent' as a standard CDE component

cde-core/resource/resources/base/components/others/TemplateComponentRender.xml, cde-core/resource/resources/custom/properties/Template/property.xml, cde-pentaho5/solution/pentaho-cdf-dd/pentaho-cdf-dd-require/tests/TemplateComponent/githubStats.ktr, cde-pentaho5/solution/pentaho-cdf-dd/pentaho-cdf-dd-require/tests/TemplateComponent/templateComponent.cda, cde-pentaho5/solution/pentaho-cdf-dd/pentaho-cdf-dd-require/tests/TemplateComponent/templateComponent.cdfde, cde-pentaho5/solution/pentaho-cdf-dd/pentaho-cdf-dd-require/tests/TemplateComponent/templateComponent.wcdf, cde-pentaho5/solution/pentaho-cdf-dd/tests/TemplateComponent/githubStats.ktr, cde-pentaho5/solution/pentaho-cdf-dd/tests/TemplateComponent/templateComponent.cda, cde-pentaho5/solution/pentaho-cdf-dd/tests/TemplateComponent/templateComponent.cdfde, cde-pentaho5/solution/pentaho-cdf-dd/tests/TemplateComponent/templateComponent.wcdf
- exposing Template Component in CDE
=> [CDF-494] Incorporate Template Component into CDF

cde-pentaho/build.properties
=> [CLEANUP] - fix CDE 4.8 build

cde-pentaho5/resource/js/cde-pentaho-require-js-cfg.js, cde-pentaho5/resource/resources/custom/amd-components/DashboardComponent/DashboardComponent.ext.js, cde-pentaho5/solution/pentaho-cdf-dd/pentaho-cdf-dd-require/dashboard/template.html, cde-pentaho5/solution/pentaho-cdf-dd/pentaho-cdf-dd-require/embeddedSample/embedded.html, cde-pentaho5/solution/pentaho-cdf-dd/pentaho-cdf-dd-require/embeddedSample/myModule.js, cde-pentaho5/solution/pentaho-cdf-dd/pentaho-cdf-dd-require/embeddedSample/template.html
- added the dashboard plugin endpoint configuration to cde-pentaho-require-js-cfg.js
- updated samples
=> [CDE-562] - Create a requirejs loader plugin for loading dashboard modules

cde-core/src/pt/webdetails/cdf/dd/CdeConstants.java, cde-core/src/pt/webdetails/cdf/dd/model/inst/reader/cdfdejs/CdfdeJsDashboardReader.java, cde-core/src/pt/webdetails/cdf/dd/render/RenderResources.java, cde-core/src/pt/webdetails/cdf/dd/render/layout/ResourceCodeRender.java, cde-core/src/pt/webdetails/cdf/dd/render/layout/ResourceFileRender.java, cde-core/src/pt/webdetails/cdf/dd/render/layout/ResourceRender.java, cde-core/test-src/pt/webdetails/cdf/dd/render/RenderResourcesTest.java, cde-core/test-src/pt/webdetails/cdf/dd/render/layout/ResourceRenderTest.java, cde-pentaho5/src/pt/webdetails/cdf/dd/api/ResourcesApi.java
- restoring the capability to render legacy (.cdfde) LayoutResource type
=> [CDE-563][CLEANUP]

cde-core/resource/js/cdf-dd-components-generic.js
=> [CDE-450] Changing parameters order was not being kept when submitted

cde-core/src/pt/webdetails/cdf/dd/render/CdaRenderer.java, cde-pentaho5/solution/pentaho-cdf-dd/pentaho-cdf-dd-require/tests/Queries/MqlQuery/index.locale, cde-pentaho5/solution/pentaho-cdf-dd/pentaho-cdf-dd-require/tests/Queries/MqlQuery/index.xml, cde-pentaho5/solution/pentaho-cdf-dd/pentaho-cdf-dd-require/tests/Queries/MqlQuery/mqlDash.cda, cde-pentaho5/solution/pentaho-cdf-dd/pentaho-cdf-dd-require/tests/Queries/MqlQuery/mqlDash.cdfde, cde-pentaho5/solution/pentaho-cdf-dd/pentaho-cdf-dd-require/tests/Queries/MqlQuery/mqlDash.wcdf, cde-pentaho5/solution/pentaho-cdf-dd/pentaho-cdf-dd-require/tests/Queries/index.locale, cde-pentaho5/solution/pentaho-cdf-dd/pentaho-cdf-dd-require/tests/Queries/index.xml, cde-pentaho5/solution/pentaho-cdf-dd/tests/Queries/MqlQuery/index.locale, cde-pentaho5/solution/pentaho-cdf-dd/tests/Queries/MqlQuery/index.xml, cde-pentaho5/solution/pentaho-cdf-dd/tests/Queries/MqlQuery/mqlDash.cda, cde-pentaho5/solution/pentaho-cdf-dd/tests/Queries/MqlQuery/mqlDash.cdfde, cde-pentaho5/solution/pentaho-cdf-dd/tests/Queries/MqlQuery/mqlDash.wcdf, cde-pentaho5/solution/pentaho-cdf-dd/tests/Queries/index.locale, cde-pentaho5/solution/pentaho-cdf-dd/tests/Queries/index.xml
- added legacy and AMD samples
=> [CDE-579] save CDA queries using CDATA sections

build.xml, cde-core/build.xml, cde-pentaho/build.xml, cde-pentaho5/build.xml
- overwrite subfloor default value 'no'
=> [TEST] make build fail when junit test errors or failures occur

cde-core/build.properties, cde-core/ivy.xml, cde-pentaho5/build.properties, cde-pentaho5/ivy.xml
- also moved all spring revisions to build.properties
=> spring.framework upgraded to 3.2.14.RELEASE

cde-pentaho5/solution/pentaho-cdf-dd/pentaho-cdf-dd-require/tests/VisualizationApi/VisualizationAPIreference.cdfde, cde-pentaho5/solution/pentaho-cdf-dd/tests/VisualizationAPIreference.cdfde
* Changing VizAPI 3 visualization ids.
@pamval please review.
=> [BACKLOG-4144] - Full VizAPI/Analyzer Support for 3rd-party, Legacy Visualizations

cde-pentaho5/solution/pentaho-cdf-dd/pentaho-cdf-dd-require/vizapi/chord/chord.cda, cde-pentaho5/solution/pentaho-cdf-dd/pentaho-cdf-dd-require/vizapi/chord/chord.cdfde, cde-pentaho5/solution/pentaho-cdf-dd/pentaho-cdf-dd-require/vizapi/chord/chord.wcdf, cde-pentaho5/solution/pentaho-cdf-dd/pentaho-cdf-dd-require/vizapi/chord/chord.wcdf.locale, cde-pentaho5/solution/pentaho-cdf-dd/pentaho-cdf-dd-require/vizapi/chord/index.properties, cde-pentaho5/solution/pentaho-cdf-dd/pentaho-cdf-dd-require/vizapi/chord/index.xml, cde-pentaho5/solution/pentaho-cdf-dd/pentaho-cdf-dd-require/vizapi/geo/geo.cda, cde-pentaho5/solution/pentaho-cdf-dd/pentaho-cdf-dd-require/vizapi/geo/geo.cdfde, cde-pentaho5/solution/pentaho-cdf-dd/pentaho-cdf-dd-require/vizapi/geo/geo.wcdf, cde-pentaho5/solution/pentaho-cdf-dd/pentaho-cdf-dd-require/vizapi/geo/geo.wcdf.locale, cde-pentaho5/solution/pentaho-cdf-dd/pentaho-cdf-dd-require/vizapi/geo/index.properties, cde-pentaho5/solution/pentaho-cdf-dd/pentaho-cdf-dd-require/vizapi/geo/index.xml, cde-pentaho5/solution/pentaho-cdf-dd/pentaho-cdf-dd-require/vizapi/index.properties, cde-pentaho5/solution/pentaho-cdf-dd/pentaho-cdf-dd-require/vizapi/index.xml
**NOTE**: merging into master, to go with 6.0.
* Added a sample with the Chord Diagram, that also uses Visual Map annotations on the DataTable
* Added a sample with the GEO map, that also uses Visual Map and GEO roles' annotations on the DataTable
@pamval please review.
=> [BACKLOG-1427] - General Visualization API Refactoring

cde-core/src/pt/webdetails/cdf/dd/util/JsonUtils.java, cde-pentaho5/src/pt/webdetails/cdf/dd/api/DatasourcesApi.java, cde-pentaho5/src/pt/webdetails/cdf/dd/api/EditorApi.java, cde-pentaho5/src/pt/webdetails/cdf/dd/api/PluginsApi.java, cde-pentaho5/src/pt/webdetails/cdf/dd/api/RenderApi.java, cde-pentaho5/src/pt/webdetails/cdf/dd/api/ResourcesApi.java, cde-pentaho5/src/pt/webdetails/cdf/dd/api/SyncronizerApi.java, cde-pentaho5/src/pt/webdetails/cdf/dd/api/VersionApi.java, cde-pentaho5/test-src/pt/webdetails/cdf/dd/api/RenderApiForTesting.java, cde-pentaho5/test-src/pt/webdetails/cdf/dd/api/RenderApiTest.java, cde-pentaho5/test-src/pt/webdetails/cdf/dd/api/SynchronizerApiForTesting.java, cde-pentaho5/test-src/pt/webdetails/cdf/dd/api/SynchronizerApiTest.java
- make sure JSON endpoints set HTTP response header ContentType to "application/json;charset=UTF-8"
- make better use of the Jersey resources available
- unit tests
=> [CDF-642] "not well-formed" warning when loading client-side JSON in Firefox

cde-pentaho5/src/pt/webdetails/cdf/dd/DashboardDesignerFileInfoGenerator.java, cde-pentaho5/src/pt/webdetails/cdf/dd/PentahoCdeEnvironment.java
=> [CLEANUP] - Codestyle changes

cde-pentaho5/solution/pentaho-cdf-dd/tests/NewMapComponent/FullMapTest.cdfde
- fixed paths for CSS file resources and salesGraphForMarker.js in FullMapTest legacy sample dashboard
=> [DOC] NewMapComponent

cde-core/src/pt/webdetails/cdf/dd/CdeConstants.java, cde-pentaho5/resource/settings.xml, cde-pentaho5/resource/settings.xml.disabled, cde-pentaho5/src/pt/webdetails/cdf/dd/api/ResourcesApi.java
Conflicts:
cde-core/src/pt/webdetails/cdf/dd/CdeConstants.java
cde-pentaho5/src/pt/webdetails/cdf/dd/api/ResourcesApi.java
=> [CDE-652] - CDE now respects the downloadable-formats setting

cde-core/resource/js/cdf-dd.js, cde-core/test-js/legacy/cdf-dd-spec.js, cde-core/test-js/legacy/mockDashboards.js
=> [CDE-659] CDE save new dashboard: Description field isn't being considered

cde-core/resource/js/cdf-dd.js, cde-core/test-js/legacy/cdf-dd-spec.js, cde-core/test-js/legacy/mockDashboards.js
=> [CDE-659][Cherry-Pick] CDE save new dashboard: Description field isn't being considered

cde-pentaho5/ivy.xml
=> [CLEANUP] - Updating cpf version due to artefact cleanup

cde-pentaho5/solution/pentaho-cdf-dd/pentaho-cdf-dd-require/tests/FilterComponent/filter_reference.cdfde, cde-pentaho5/solution/pentaho-cdf-dd/tests/FilterComponent/filter_reference.cdfde
- Some changes in the files were missing
=> [CDF-676] cherry-pick c74e26420781dd30848ffae09b0f9175b2bad7ac

cde-core/resource/js/cdf-dd-components-generic.js
@pamval @jvelasques please review
=> [CDE-647] Cancel Remove Row Selection was not enabling all inputs

cde-core/resource/css/master.css, cde-core/resource/css/stringlist.css, cde-core/resource/js/cdf-dd-components-generic.js, cde-core/src/pt/webdetails/cdf/dd/render/cda/Parameters.java, cde-core/test-js/legacy/cdf-dd-components-generic-spec.js, cde-core/test-src/pt/webdetails/cdf/dd/render/cda/ParametersTest.java
UX team didn't responde to the email today, so as agreed here are the changes made.
=> [CDE-431] When adding a parameter of the Date type to a query it returns a 501 error

cde-pentaho5/solution/pentaho-cdf-dd/pentaho-cdf-dd-require/tests/Queries/Compound/compoundQueryDash.cda, cde-pentaho5/solution/pentaho-cdf-dd/pentaho-cdf-dd-require/tests/Queries/Compound/compoundQueryDash.cdfde, cde-pentaho5/solution/pentaho-cdf-dd/pentaho-cdf-dd-require/tests/Queries/Compound/compoundQueryDash.wcdf, cde-pentaho5/solution/pentaho-cdf-dd/pentaho-cdf-dd-require/tests/Queries/Compound/index.locale, cde-pentaho5/solution/pentaho-cdf-dd/pentaho-cdf-dd-require/tests/Queries/Compound/index.xml, cde-pentaho5/solution/pentaho-cdf-dd/tests/Queries/Compound/compoundQueryDash.cda, cde-pentaho5/solution/pentaho-cdf-dd/tests/Queries/Compound/compoundQueryDash.cdfde, cde-pentaho5/solution/pentaho-cdf-dd/tests/Queries/Compound/compoundQueryDash.wcdf, cde-pentaho5/solution/pentaho-cdf-dd/tests/Queries/Compound/index.locale, cde-pentaho5/solution/pentaho-cdf-dd/tests/Queries/Compound/index.xml
=> [CDA-104] Calculated Column at Compound Queries

cde-pentaho5/resource/js/cdf-dd-base.js, cde-pentaho5/test-js/legacy/cdf-dd-base-spec.js
=> [CDE-679] As a user, I would like to use custom styles in a Sparkl Application

cde-core/resource/js/cdf-dd-components-charts.js, cde-core/resource/js/cdf-dd-components-generic.js, cde-core/resource/js/cdf-dd-components-selectors.js, cde-core/resource/js/cdf-dd-tablemanager.js, cde-core/resource/js/cdf-dd.js, cde-core/src/pt/webdetails/cdf/dd/model/inst/writer/cdfrunjs/properties/CdfRunJsPropertyBindingWriter.java, cde-core/test-js/legacy/cdf-dd-components-generic-spec.js, cde-core/test-js/legacy/cdf-dd-components-spec.js, cde-core/test-js/legacy/cdf-dd-datasources-editor-spec.js, cde-core/test-js/legacy/cdf-dd-tablemanager-spec.js, cde-core/test-js/legacy/mockDashboards.js, cde-core/test-src/pt/webdetails/cdf/dd/model/inst/writer/cdfrunjs/properties/CdfRunJsPropertyBindingWriterForTests.java, cde-core/test-src/pt/webdetails/cdf/dd/model/inst/writer/cdfrunjs/properties/CdfRunJsPropertyBindingWriterTest.java
=> [CDE-671, CDE-672, CDE-673, CDE-674] - Sanitizing editor input

cde-core/resource/js/cdf-dd-components.js, cde-core/resource/js/cdf-dd-datasources.js, cde-core/resource/js/cdf-dd-layout.js, cde-core/resource/js/cdf-dd-tablemanager.js, cde-core/resource/js/cdf-dd.js
=> [CDE-660] Layout Tree - Keyboard commands do not work when opened in a PUC tab

cde-core/resource/css/master.css, cde-core/resource/css/stringlist.css, cde-core/resource/js/cdf-dd-components-generic.js
=> [CDE-431] Changed new input to include UX Team review

cde-core/resource/js/cdf-dd-components-generic.js
=> [CDE-431] Fixed bug causing the disabled style being removed from all row patterns

cde-core/resource/js/cdf-dd-components-generic.js, cde-core/resource/resources/base/properties/BandedMode.xml, cde-core/resource/resources/base/properties/CacheKeys.xml, cde-core/resource/resources/base/properties/CdaCalculatedColumns.xml, cde-core/resource/resources/base/properties/CdaColumns.xml, cde-core/resource/resources/base/properties/Output.xml, cde-core/resource/resources/base/properties/Parameters.xml
=> [CDE-204] MDX datasource: Tooltips Improvement

cde-core/resource/js/cdf-dd-components.js, cde-core/resource/js/cdf-dd-datasources.js, cde-core/resource/js/cdf-dd-palletemanager.js, cde-core/test-js/legacy/cdf-dd-components-spec.js, cde-core/test-js/legacy/cdf-dd-datasources-spec.js
=> [CLEANUP][CDE-202] Datasources improvements on CDE

cde-core/test-js/legacy/cdf-dd-layout-spec.js
=> [CDE-686] CDE javascript unit test fix and cleanup

cde-core/resource/js/cdf-dd-components-generic.js
- created ArrayNoParamRenderer for single dimension renderers without autocomplete
- Did some cleanup by reordering the various renderers, so that they can be found in code more easily
=> [CDE-697] Column Header in Table Component shouldn't list Single Parameters

cde-core/resource/js/cdf-dd-components-generic.js, cde-core/resource/resources/base/properties/ColSearchable.xml, cde-core/resource/resources/base/properties/ExpandParameters.xml, cde-core/resource/resources/base/properties/ExtraOptions.xml, cde-core/resource/resources/custom/properties/FreeForm/property.xml
=> [CDE-721] TableComponent properties popups with wrong titles

cde-core/resource/css/master.css, cde-core/resource/js/cdf-dd-tablemanager.js, cde-core/test-js/legacy/cdf-dd-base-spec.js, cde-core/test-js/legacy/cdf-dd-spec.js, cde-core/test-js/legacy/cdf-dd-tablemanager-spec.js, cde-core/test-js/legacy/mockDashboards.js
=> [CDE-720] Focus issues when using mouse to edit properties in CDE Editor

cde-core/resource/css/master.css, cde-core/resource/js/cdf-dd-components.js, cde-core/resource/js/cdf-dd-datasources.js, cde-core/resource/js/cdf-dd-layout.js, cde-core/resource/js/cdf-dd-tablemanager.js, cde-core/resource/js/cdf-dd.js, cde-core/src/pt/webdetails/cdf/dd/CdeConstants.java, cde-core/src/pt/webdetails/cdf/dd/model/inst/writer/cdfrunjs/dashboard/amd/CdfRunJsDashboardModuleWriter.java, cde-core/src/pt/webdetails/cdf/dd/util/Utils.java, cde-core/test-js/legacy/cdf-dd-tablemanager-spec.js, cde-core/test-src/pt/webdetails/cdf/dd/model/inst/writer/cdfrunjs/dashboard/amd/CdfRunJsDashboardModuleWriterTest.java
@pamval @carlosrusso please review
=> [CLEANUP] - Reverting 596cdb7f551742b34e6ad10d6b8b8ab818a70ab8

cde-pentaho5/config/cde.build.compile.js
=> [CDF-787] - Fixing module path override in build time

cde-core/resource/resources/custom/amd-components/Map/engines/google/MapEngineGoogle.js, cde-core/resource/resources/custom/amd-components/Map/engines/google/MapOverlay.js, cde-core/resource/resources/custom/components/Map/Map.js
@pamval please review. Should this be backported to 5.x?
=> [CDE-749] NewMapComponent, MapEngine Google: Reviewed mouse interactions

cde-pentaho5/config/cde.build.compile.js
@pamval please review. This is a cherry-pick for a similar problem in master
=> [CDF-787] - Fixing module path override in build time (cherry-pick)

cde-core/resource/js/cdf-dd-components-generic.js
=> [CDE-205] - Update to eliminate spaces

cde-core/resource/js/cdf-dd-components-selectors.js, cde-core/resource/js/cdf-dd-tablemanager.js, cde-core/resource/js/cdf-dd-util.js, cde-core/resource/js/cdf-dd.js, cde-core/test-js/legacy/cdf-dd-components-selectors-spec.js, cde-pentaho/resource/js/cdf-dd-base.js
- replace `eval()` with `JSON.parse()` in cdf-dd-util.js, cdf-dd-util.js, cdf-dd-base.js
@pamval, @plagoa, review it please
=> [PPP-3455] - Dynamic code injection vulnerabilities found

cde-pentaho5/solution/pentaho-cdf-dd/tests/ViewManager/viewManager.cdfde
updated sample that was missing the changes @pamval please review
last pull: https://github.com/webdetails/cde/pull/674
=> [CDE-695] - View Manager - deleting view

cde-core/resource/js/cdf-dd-components-selectors.js, cde-core/resource/js/cdf-dd-tablemanager.js, cde-core/resource/js/cdf-dd-util.js, cde-core/resource/js/cdf-dd.js, cde-pentaho/resource/js/cdf-dd-base.js
- replace `eval()` with `JSON.parse()` in cdf-dd-util.js, cdf-dd-util.js, cdf-dd-base.js
- in ListenersRenderer, amend self-written `obj.toString()` to return well-formed representation
- also change `value` generating algorithm in cdf-dd-tablemanager.js to follow ECMA standard of JSON string representation
(adopted from 467bc718dbbbe498a6cd857494e88573ef393ddf)
@afrjorge, review it please. This is a backport of https://github.com/webdetails/cde/pull/678
=> [SP-2383] - Backport of PPP-3455 - Dynamic code injection vulnerabilities found (6.0 Suite)

cde-pentaho5/resource/resources/custom/amd-components/Dashboard/DashboardComponent.js, cde-pentaho5/test-js/components/DashboardComponent-spec.js
=> [CDE-826] - DashboardComponent: Expose a way to turn on and off the

cde-core/config/karma.ci.conf.js, cde-core/config/karma.conf.js, cde-pentaho5/config/karma.ci.conf.js, cde-pentaho5/config/karma.conf.js
@diogofscmariano @pamval please review
=> [TEST] Add HTML coverage reports

cde-pentaho5/build.properties, cde-pentaho5/ivy.xml
=> [CLEANUP] - correcting mondrian revisions

cde-pentaho5/resource/render.includes.properties
@diogofscmariano left over from the previous pull request
=> [PPP-3577] - Removing ViewManager component from CDE core

cde-core/resource/resources/base/properties/Height.xml, cde-core/resource/resources/base/properties/Width.xml
=> [CDE-835] Set a default value for Width and Height in chart components different than 0

cde-core/resource/resources/custom/amd-components/cgg/CggComponent.js, cde-core/resource/resources/custom/components/cgg/cgg-implementation.js
=> [CDE-857] CGG Dial Chart is not responding correctly to functions in Pre Execution

cde-core/resource/resources/custom/amd-components/cgg/CggComponent.js, cde-core/resource/resources/custom/components/cgg/cgg-implementation.js
Reverts webdetails/cde#722
this should've gone to master and not to 6.1
=> Revert "[CDE-857] CGG Dial Chart is not responding correctly to functions in Pre Execution"

cde-core/resource/resources/custom/components/Map/component.xml
=> [CDE-874] Updated list of available tilesets and modified the default.

cde-core/resource/resources/custom/amd-components/cgg/CggComponent.js, cde-core/resource/resources/custom/components/cgg/cgg-implementation.js
=> [SP-2958] Backport of CDE-822 - CGG Dial Component replicates when parameters change (6.1 Suite)

cde-core/src/pt/webdetails/cdf/dd/util/Utils.java, cde-pentaho/src/pt/webdetails/cdf/dd/DashboardDesignerFileInfoGenerator.java, cde-pentaho5/src/pt/webdetails/cdf/dd/DashboardDesignerFileInfoGenerator.java
@pamval, @mbatchelor, @tgf,
the PR should be merged not earlier than: webdetails/cpf#99
Thanks.
=> [PPP-3506] - XXE Security Vulnerability in xml parsers

cde-core/resource/resources/custom/amd-components/exportButton/ExportButtonComponent.js, cde-core/resource/resources/custom/components/exportButton/component.xml, cde-core/resource/resources/custom/components/exportButton/exportButton.js, cde-core/test-js/components/ExportButtonComponent-spec.js, cde-core/test-resources/resource/resources/custom/components/exportButton/component.xml, cde-core/test-src/pt/webdetails/cdf/dd/model/inst/writer/cdfrunjs/components/legacy/CdfRunJsParameterComponentWriterTest.java, cde-core/test-src/pt/webdetails/cdf/dd/model/inst/writer/cdfrunjs/dashboard/amd/CdfRunJsDashboardWriterTest.java
-added test, changed default behaviour
=> [CDE-849] Export of table with paginate server side set as true is only exporting 10 results in a kettle data source

cde-core/resource/js/cdf-dd.js
=> [PDB-1926] 'Bad' Error when using PUC via iFrame when Saving Dashboard to Folder to which user has no permissions

cde-core/resource/resources/custom/amd-components/exportButton/ExportButtonComponent.js, cde-core/resource/resources/custom/components/exportButton/component.xml, cde-core/resource/resources/custom/components/exportButton/exportButton.js, cde-core/test-js/components/ExportButtonComponent-spec.js, cde-core/test-resources/resource/resources/custom/components/exportButton/component.xml, cde-core/test-src/pt/webdetails/cdf/dd/model/inst/writer/cdfrunjs/components/legacy/CdfRunJsParameterComponentWriterTest.java, cde-core/test-src/pt/webdetails/cdf/dd/model/inst/writer/cdfrunjs/dashboard/amd/CdfRunJsDashboardWriterTest.java
=> [SP-3039] Backport of CDE-849 - Export of table with paginate server side set as true is only exporting 10 results in a kettle data source (6.1 Suite)

cde-core/resource/resources/custom/amd-components/exportButton/ExportButtonComponent.js, cde-core/resource/resources/custom/components/exportButton/component.xml, cde-core/resource/resources/custom/components/exportButton/exportButton.js, cde-core/test-js/components/ExportButtonComponent-spec.js, cde-core/test-resources/resource/resources/custom/components/exportButton/component.xml, cde-core/test-src/pt/webdetails/cdf/dd/model/inst/writer/cdfrunjs/components/legacy/CdfRunJsParameterComponentWriterTest.java, cde-core/test-src/pt/webdetails/cdf/dd/model/inst/writer/cdfrunjs/dashboard/amd/CdfRunJsDashboardWriterTest.java
=> [SP-3038] Backport of CDE-849 - Export of table with paginate server side set as true is only exporting 10 results in a kettle data source (7.0 Suite)

cde-core/resource/js/cdf-dd.js
=> [SP-3078] Backport of PDB-1926 - 'Bad' Error when using PUC via iFrame when Saving Dashboard to Folder to which user has no permissions (7.0 Suite)

cde-core/resource/js/cdf-dd.js
=> [SP-3079] Backport of PDB-1926 - 'Bad' Error when using PUC via iFrame when Saving Dashboard to Folder to which user has no permissions (6.1 Suite)

cde-core/resource/css/about.fancybox.css, cde-core/resource/css/documentation.fancybox.css, cde-pentaho/solution/pentaho-cdf-dd/template.css, cde-pentaho5/solution/pentaho-cdf-dd/pentaho-cdf-dd-require/embeddedSample/template.css, cde-pentaho5/solution/pentaho-cdf-dd/pentaho-cdf-dd-require/template.css, cde-pentaho5/solution/pentaho-cdf-dd/template.css
@pamval @pedrofvteixeira @smaring please take a look
=> [CDE-871]-Avoid hardcoding a protocol

cde-pentaho/ivy.xml, cde-pentaho5/ivy.xml
subject to merge of https://github.com/pentaho/pentaho-commons-json/pull/8
=> [ENGOPS-2639] json GAV change

cde-pentaho5/solution/pentaho-cdf-dd/pentaho-cdf-dd-require/tests/VisualizationApi/VisualizationAPIreference.cda, cde-pentaho5/solution/pentaho-cdf-dd/pentaho-cdf-dd-require/tests/VisualizationApi/VisualizationAPIreference.cdfde, cde-pentaho5/solution/pentaho-cdf-dd/tests/VisualizationAPIreference.cda, cde-pentaho5/solution/pentaho-cdf-dd/tests/VisualizationAPIreference.cdfde
* Changed both samples to use the CCC bar chart
@pentaho/millenniumfalcon, @carlosrusso, @graimundo, @marcovala, @davidmsantos90, @nantunes please review.
Depends on https://github.com/webdetails/cdf/pull/913
=> [BACKLOG-13668] VizAPI views restructuring

cde-core/resource/resources/base/properties/cccActiveSliceRadius.xml, cde-core/resource/resources/base/properties/cccBarSizeMax.xml, cde-core/resource/resources/base/properties/cccBarSizeRatio.xml, cde-core/resource/resources/base/properties/cccCompatVersion.xml, cde-core/resource/resources/base/properties/cccContentMargins.xml, cde-core/resource/resources/base/properties/cccContentPaddings.xml, cde-core/resource/resources/base/properties/cccDotsVisible.xml, cde-core/resource/resources/base/properties/cccLegendFont.xml, cde-core/resource/resources/base/properties/cccLegendItemPadding.xml, cde-core/resource/resources/base/properties/cccLegendMargins.xml, cde-core/resource/resources/base/properties/cccLegendMarkerSize.xml, cde-core/resource/resources/base/properties/cccLegendOverflow.xml, cde-core/resource/resources/base/properties/cccLegendPaddings.xml, cde-core/resource/resources/base/properties/cccLegendPosition.xml, cde-core/resource/resources/base/properties/cccLegendTextMargin.xml, cde-core/resource/resources/base/properties/cccLinesVisible.xml, cde-core/resource/resources/base/properties/cccMargins.xml, cde-core/resource/resources/base/properties/cccPaddings.xml, cde-core/resource/resources/base/properties/cccTitlePosition.xml
- Removed property default values to allow their override in runtime for new dashboards
@dcleao @afrjorge please review
=> [BACKLOG-14077] 

cde-pentaho5/ivy.xml, cde-pentaho5/src/pt/webdetails/cdf/dd/api/EditorApi.java, cde-pentaho5/src/pt/webdetails/cdf/dd/api/RenderApi.java, cde-pentaho5/src/pt/webdetails/cdf/dd/api/ResourcesApi.java, cde-pentaho5/src/pt/webdetails/cdf/dd/api/SyncronizerApi.java, cde-pentaho5/src/pt/webdetails/cdf/dd/api/XSSHelper.java, cde-pentaho5/test-src/pt/webdetails/cdf/dd/api/EditorApiTest.java, cde-pentaho5/test-src/pt/webdetails/cdf/dd/api/RenderApiTest.java, cde-pentaho5/test-src/pt/webdetails/cdf/dd/api/SynchronizerApiTest.java, cde-pentaho5/test-src/pt/webdetails/cdf/dd/api/XSSHelperTest.java
#767 backport 
@pamval @mbatchelor  @mchen-len-son
=> [SP-3351][CDF-964]-Reflected XSS prevention

cde-pentaho5/ivy.xml, cde-pentaho5/src/pt/webdetails/cdf/dd/api/EditorApi.java, cde-pentaho5/src/pt/webdetails/cdf/dd/api/RenderApi.java, cde-pentaho5/src/pt/webdetails/cdf/dd/api/ResourcesApi.java, cde-pentaho5/src/pt/webdetails/cdf/dd/api/SyncronizerApi.java, cde-pentaho5/src/pt/webdetails/cdf/dd/api/XSSHelper.java, cde-pentaho5/test-src/pt/webdetails/cdf/dd/api/EditorApiTest.java, cde-pentaho5/test-src/pt/webdetails/cdf/dd/api/RenderApiTest.java, cde-pentaho5/test-src/pt/webdetails/cdf/dd/api/SynchronizerApiTest.java, cde-pentaho5/test-src/pt/webdetails/cdf/dd/api/XSSHelperTest.java
=> [SP-3352][CDF-964]-Reflected XSS prevention

cde-core/resource/resources/base/properties/cccBaseAxisLabelRotationDirection.xml, cde-core/resource/resources/base/properties/cccBaseAxisOverlappedLabelsMode.xml
- Added exception for baseAxisOverlappedLabelsMode and baseAxisLabelRotationDirection
@dcleao @afrjorge please review
=> [BACKLOG-14077]

cde-core/ivy.xml, cde-core/src/pt/webdetails/cdf/dd/CdeConstants.java, cde-core/src/pt/webdetails/cdf/dd/util/CorsUtil.java, cde-pentaho5/resource/settings.xml
@pamval @mbatchelor @mchen-len-son please review
=> [CDA-211]-Implement a whitelist for CORS

cde-core/resource/resources/base/properties/cccUseShapes.xml
=> [BACKLOG-14077] - Removed default for useShapes

cde-core/resource/resources/base/properties/cccHoverable.xml, cde-core/resource/resources/base/properties/cccSelectable.xml
=> [BACKLOG-14077] - Reverted changes to Selectable and Hoverable in CDE

cde-core/resource/resources/custom/amd-components/Map/Map.tileServices.js, cde-core/resource/resources/custom/components/Map/Map.js
@webdetails/millenniumfalcon Please review
=> [BACKLOG-16406] Modified default tileset to OpenStreetMap’s

cde-core/src/pt/webdetails/cdf/dd/model/inst/writer/cdfrunjs/dashboard/amd/PentahoCdfRunJsDashboardWriteContext.java, cde-core/src/pt/webdetails/cdf/dd/model/inst/writer/cdfrunjs/dashboard/legacy/PentahoCdfRunJsDashboardWriteContext.java, cde-core/test-src/pt/webdetails/cdf/dd/model/inst/writer/cdfrunjs/dashboard/amd/PentahoCdfRunJsDashboardWriteContextForTesting.java, cde-core/test-src/pt/webdetails/cdf/dd/model/inst/writer/cdfrunjs/dashboard/amd/PentahoCdfRunJsDashboardWriteContextTest.java, cde-core/test-src/pt/webdetails/cdf/dd/model/inst/writer/cdfrunjs/dashboard/legacy/PentahoCdfRunJsDashboardWriteContextForTesting.java, cde-core/test-src/pt/webdetails/cdf/dd/model/inst/writer/cdfrunjs/dashboard/legacy/PentahoCdfRunJsDashboardWriteContextTest.java
- fixed invalid paths for system resources
=> [BACKLOG-16488] - App Builder (Sparkl) not working

cde-pentaho5/src/pt/webdetails/cdf/dd/InterPluginBroker.java, cde-pentaho5/src/pt/webdetails/cdf/dd/api/RenderApi.java
- parameter "secure" was added
- the called method was changed to the new one
=> [CDE-908] Embedding a CDE dashboard fails when using HTTPS

cde-core/build.properties, cde-core/ivy.xml, cde-pentaho/build.properties, cde-pentaho/ivy.xml, cde-pentaho5/build.properties, cde-pentaho5/ivy.xml
WARNING!  FOR MERGE BY PROCESS ONLY PLEASE!
=> [ENGOPS-1757] version name consolidation

assemblies/platform/pentaho-cdf-dd/src/main/resources-filtered/version.xml
- added version.xml resource file
=> [BACKLOG-20079] Mavenize the CDE plugin

core/impl/src/main/java/pt/webdetails/cdf/dd/model/inst/writer/cdfrunjs/components/amd/CdfRunJsDataSourceComponentWriter.java, core/impl/src/test/java/pt/webdetails/cdf/dd/model/inst/writer/cdfrunjs/components/amd/CdfRunJsDataSourceComponentWriterTest.java
=> [BACKLOG-21152] Wrong order, causing solr query to be writen incorrectly

pom.xml
@tmcsantos @lgrill-pentaho @emartin-pentaho
=> [CLEANUP] use version names from version.properties

assemblies/platform/pentaho-cdf-dd-samples/src/main/resources/plugin-samples/pentaho-cdf-dd/pentaho-cdf-dd-require/tests/VisualizationApi/VisualizationAPIreference.cdfde, assemblies/platform/pentaho-cdf-dd-samples/src/main/resources/plugin-samples/pentaho-cdf-dd/tests/VisualizationAPIreference.cdfde
Depends on pentaho/pentaho-platform-plugin-common-ui#1249.
=> [BACKLOG-21390] VizAPI 3.0 stock visualizations: Use the new Visual Role's capabilities

assemblies/cde-renderer/feature/pom.xml, assemblies/pdi/cde-plugin-pdi/pom.xml, assemblies/pdi/pom.xml
*Depends on* https://github.com/webdetails/cpf/pull/120
Marked as provided the dependencies for packages being made available via karaf/etc/custom.properties
@webdetails/millenniumfalcon @afrjorge please review
=> [BACKLOG-22035] - Remove from feature dependencies being imported from non OSGi world

components/impls/core/src/main/javascript/cde-core-require-js-cfg.js
- fix cde custom components path
=> [BACKLOG-21718] Create webpackage assembly for CDE components

components/impls/core/src/main/javascript/properties/DataServiceQuery.xml
@plagoa @marcoslarsen @francisco-guilherme please review
=> [BACKLOG-22395] Default SQL query on a CDE dataservice datasource

components/impls/core/src/main/javascript/properties/WindowEvery.xml, components/impls/core/src/main/javascript/properties/WindowLimit.xml, components/impls/core/src/main/javascript/properties/WindowMode.xml, components/impls/core/src/main/javascript/properties/WindowSize.xml, webclient/impls/core/src/main/javascript/cdf-dd-components-others.js
dataservices, for row and time based windows.
@pentaho/kashyyyk Please review.
Depends on https://github.com/pentaho/pdi-dataservice-plugin/pull/156
=> [BACKLOG-22231] - Control window streaming parameters in streaming

components/impls/core/src/main/javascript/properties/WindowEvery.xml, components/impls/core/src/main/javascript/properties/WindowLimit.xml, components/impls/core/src/main/javascript/properties/WindowMode.xml, components/impls/core/src/main/javascript/properties/WindowSize.xml
@plagoa @joaormf @francisco-guilherme Please review
=> [FIX] - Attribute order.

components/impls/core/src/main/javascript/components/CCC.xml, components/impls/core/src/main/javascript/properties/DataAdditiveMode.xml, components/impls/core/src/main/javascript/properties/RenderMode.xml
=> [BACKLOG-22074] - added renderMode and dataAdditiveMode properties

core/impl/src/main/java/pt/webdetails/cdf/dd/model/inst/writer/cdfrunjs/dashboard/amd/CdfRunJsDashboardWriter.java, core/impl/src/test/java/pt/webdetails/cdf/dd/model/inst/writer/cdfrunjs/dashboard/amd/CdfRunJsDashboardWriterTest.java
- fix RequireJS configurations with paths containing white spaces
=> [BACKLOG-22388] Update Ctools sample Steel Wheels dashboard in the product

core/impl/src/main/java/pt/webdetails/cdf/dd/model/inst/writer/cdfrunjs/dashboard/CdfRunJsDashboardWriteContext.java, core/impl/src/main/java/pt/webdetails/cdf/dd/model/inst/writer/cdfrunjs/dashboard/amd/PentahoCdfRunJsDashboardWriteContext.java, core/impl/src/main/java/pt/webdetails/cdf/dd/model/inst/writer/cdfrunjs/dashboard/legacy/PentahoCdfRunJsDashboardWriteContext.java, core/impl/src/test/java/pt/webdetails/cdf/dd/model/inst/writer/cdfrunjs/dashboard/amd/PentahoCdfRunJsDashboardWriteContextForTesting.java, core/impl/src/test/java/pt/webdetails/cdf/dd/model/inst/writer/cdfrunjs/dashboard/amd/PentahoCdfRunJsDashboardWriteContextTest.java, core/impl/src/test/resources/test folder/testDashboard.wcdf
- Escaping white spaces to avoid uri normalization errors
=> [BACKLOG-22634] CTools Dashboard sample file contains errors.

pentaho/impl/src/main/java/pt/webdetails/cdf/dd/api/EditorApi.java, pentaho/impl/src/main/java/pt/webdetails/cdf/dd/api/RenderApi.java, pentaho/impl/src/main/java/pt/webdetails/cdf/dd/api/ResourcesApi.java, pentaho/impl/src/main/java/pt/webdetails/cdf/dd/api/SyncronizerApi.java
- this solves a problem in the web client, when it tries to show a file with white spaces in its path
=> [BACKLOG-22634][CLEANUP] Decoding values sent to the rest APIs before being used.

assemblies/platform/pentaho-cdf-dd-disabled/pom.xml, assemblies/platform/pentaho-cdf-dd-disabled/src/assembly/assembly.xml
@pedrofvteixeira @webdetails/millenniumfalcon please review
=> [BACKLOG-22798] Require resources weren't being included in CDE final assembly

components/impls/pentaho/src/main/javascript/components/NewMapComponent/amd/Map.ext.js
@webdetails/millenniumfalcon @pamval please review
- cherry-pick from master
=> [BACKLOG-23027] MapComponent sample has broken images for markers

assemblies/cde-renderer/feature/pom.xml, assemblies/cde-renderer/feature/src/main/feature/feature.xml, assemblies/cde-renderer/pom.xml, pom.xml
Depends on https://github.com/pentaho/pentaho-osgi-bundles/pull/262
=> [BACKLOG-22357] Use the new webpackages in the CDE/CDF renderer on Foundry

components/assemblies/cde-components-webpackage/src/main/resources-filtered/cde/package.json, components/assemblies/cde-components-webpackage/src/main/resources-filtered/cde/preconfig.js, core/impl/src/main/java/pt/webdetails/cdf/dd/CdeConstants.java, core/impl/src/main/java/pt/webdetails/cdf/dd/ICdeEnvironment.java, core/impl/src/main/java/pt/webdetails/cdf/dd/model/inst/writer/cdfrunjs/dashboard/CdfRunJsDashboardWriteContext.java, core/impl/src/main/java/pt/webdetails/cdf/dd/model/inst/writer/cdfrunjs/dashboard/CdfRunJsDashboardWriteOptions.java, core/impl/src/main/java/pt/webdetails/cdf/dd/model/inst/writer/cdfrunjs/dashboard/CdfRunJsDashboardWriteResult.java, core/impl/src/main/java/pt/webdetails/cdf/dd/model/inst/writer/cdfrunjs/dashboard/amd/CdfRunJsDashboardModuleWriter.java, core/impl/src/main/java/pt/webdetails/cdf/dd/model/inst/writer/cdfrunjs/dashboard/amd/CdfRunJsDashboardWriter.java, core/impl/src/main/java/pt/webdetails/cdf/dd/model/inst/writer/cdfrunjs/dashboard/amd/PentahoCdfRunJsDashboardWriteContext.java, core/impl/src/main/java/pt/webdetails/cdf/dd/model/inst/writer/cdfrunjs/dashboard/legacy/PentahoCdfRunJsDashboardWriteContext.java, core/impl/src/main/java/pt/webdetails/cdf/dd/render/RenderResources.java, core/impl/src/test/java/pt/webdetails/cdf/dd/model/inst/writer/cdfrunjs/dashboard/CdfRunJsDashboardWriteContextForTesting.java, core/impl/src/test/java/pt/webdetails/cdf/dd/model/inst/writer/cdfrunjs/dashboard/amd/CdfRunJsDashboardModuleWriterTest.java, core/impl/src/test/java/pt/webdetails/cdf/dd/model/inst/writer/cdfrunjs/dashboard/amd/PentahoCdfRunJsDashboardWriteContextForTesting.java, core/impl/src/test/java/pt/webdetails/cdf/dd/model/inst/writer/cdfrunjs/dashboard/amd/PentahoCdfRunJsDashboardWriteContextTest.java, core/impl/src/test/java/pt/webdetails/cdf/dd/model/inst/writer/cdfrunjs/dashboard/legacy/PentahoCdfRunJsDashboardWriteContextForTesting.java, core/impl/src/test/java/pt/webdetails/cdf/dd/model/inst/writer/cdfrunjs/dashboard/legacy/PentahoCdfRunJsDashboardWriteContextTest.java, osgi/impl/pom.xml, osgi/impl/src/main/java/org/pentaho/ctools/cde/api/RenderApi.java, osgi/impl/src/main/java/org/pentaho/ctools/cde/api/ResourcesApi.java, osgi/impl/src/main/resources-filtered/OSGI-INF/blueprint/blueprint.xml, osgi/impl/src/test/java/org/pentaho/ctools/cde/api/ResourcesApiTest.java, pentaho/impl/src/main/java/pt/webdetails/cdf/dd/api/ResourcesApi.java, pom.xml, samples/src/main/resources/samples/karaf-dashboard/index.html, samples/src/main/resources/samples/karaf-dashboard/resources/dashboard-component/dash.cdfde
Only merge after https://github.com/webdetails/cde/pull/867 :heavy_check_mark: 
and also depends on https://github.com/pentaho/pentaho-osgi-bundles/pull/262 :heavy_check_mark:
=> [BACKLOG-22043] Render a CDE dashboard with external resources on Foundry

core/impl/src/main/java/pt/webdetails/cdf/dd/model/inst/writer/cdfrunjs/dashboard/amd/CdfRunJsDashboardWriter.java
=> [BACKLOG-22043] Fix wrong method call to get a dashboard layout

assemblies/platform/pentaho-cdf-dd-samples/src/main/resources/plugin-samples/pentaho-cdf-dd/legacy/tests/CggComponent/cggComponent.cdfde, assemblies/platform/pentaho-cdf-dd-samples/src/main/resources/plugin-samples/pentaho-cdf-dd/legacy/tests/GMapsOverlay/gMapsOverlay.cdfde, assemblies/platform/pentaho-cdf-dd-samples/src/main/resources/plugin-samples/pentaho-cdf-dd/tests/CggComponent/cggComponent.cdfde, assemblies/platform/pentaho-cdf-dd-samples/src/main/resources/plugin-samples/pentaho-cdf-dd/tests/GMapsOverlay/gMapsOverlay.cdfde
=> [BACKLOG-23494] - DEV - Change samples folder structure

assemblies/platform/pentaho-cdf-dd-samples/src/main/resources/plugin-samples/pentaho-cdf-dd/legacy/tests/VisualizationAPIreference.cdfde, assemblies/platform/pentaho-cdf-dd-samples/src/main/resources/plugin-samples/pentaho-cdf-dd/tests/VisualizationApi/VisualizationAPIreference.cdfde, components/impls/core/src/test/config/javascript/context.js, components/impls/pentaho/src/test/config/javascript/context.js, samples/src/main/resources/samples/karaf-dashboard/index.html, webclient/impls/core/src/test/config/javascript/context.js, webclient/impls/pentaho/src/test/config/javascript/context.js
Merge with:
* https://github.com/webdetails/cdf/pull/1017
Depends on pentaho/pentaho-platform-plugin-common-ui#1295.
=> [BACKLOG-23474] Refactor VizAPI module system. CDF/CDE.

assemblies/platform/pentaho-cdf-dd-samples/src/main/resources/plugin-samples/pentaho-cdf-dd/legacy/tests/VisualizationAPIreference.cdfde, assemblies/platform/pentaho-cdf-dd-samples/src/main/resources/plugin-samples/pentaho-cdf-dd/tests/VisualizationApi/VisualizationAPIreference.cdfde, components/impls/core/src/test/config/javascript/context.js, components/impls/pentaho/src/test/config/javascript/context.js, samples/src/main/resources/samples/karaf-dashboard/index.html, webclient/impls/core/src/test/config/javascript/context.js, webclient/impls/pentaho/src/test/config/javascript/context.js
@webdetails/millenniumfalcon please *squash and merge*.
Merge with: https://github.com/pentaho/pentaho-platform-plugin-common-ui/pull/1302.
=> [BACKLOG-23474] Refactor VizAPI module system.

core/impl/src/main/java/pt/webdetails/cdf/dd/structure/DashboardStructure.java, pentaho/impl/pom.xml, pentaho/impl/src/main/java/pt/webdetails/cdf/dd/api/SyncronizerApi.java, pentaho/impl/src/main/java/pt/webdetails/cdf/dd/api/XSSHelper.java, pentaho/impl/src/test/java/pt/webdetails/cdf/dd/api/SynchronizerApiTest.java, pentaho/impl/src/test/java/pt/webdetails/cdf/dd/api/XSSHelperTest.java
Merge after: https://github.com/pentaho/pentaho-platform/pull/4177
=> [BACKLOG-24203] Saved CDE files should be properly formatted and "prettified"

components/impls/core/src/main/javascript/components/NewSelectorComponent/amd/NewSelectorComponent.js, components/impls/core/src/main/javascript/components/NewSelectorComponent/legacy/NewSelector.js
NewSelectorComponent only supports 12 elements per page, but the pageSize was 54.
@pamval @duarteteixeira 
@pentaho-lmartins @ricardosilva88
=> [CDE-966] New Selector Component in CDE is not showing all values

assemblies/platform/pentaho-cdf-dd-rca/pom.xml, assemblies/platform/pentaho-cdf-dd-rca/src/assembly/assembly.xml, assemblies/platform/pentaho-cdf-dd-rca/src/main/resources/plugin.spring.xml, foundry-extensions/impl/pom.xml, foundry-extensions/impl/src/main/java/org/pentaho/ctools/cde/api/DashboardsApi.java, foundry-extensions/impl/src/main/java/org/pentaho/ctools/cde/impl/DashboardsImpl.java, foundry-extensions/impl/src/test/java/org/pentaho/ctools/cde/impl/DashboardsImplTest.java, foundry-extensions/pom.xml, pom.xml
@webdetails/bobafett please review...
=> [BACKLOG-25207] - List CDE dashboards that are available via CDE on Foundry

foundry-extensions/impl/src/main/java/org/pentaho/ctools/cde/impl/DashboardsImpl.java
It depends on https://github.com/webdetails/cpf/pull/132
=> [BACKLOG-25778] - Get metadata for the dashboards available in the CDE editor / render services

assemblies/platform/pentaho-cdf-dd/src/main/resources/lang/messages_supported_languages.properties, assemblies/platform/pentaho-cdf-dd/src/main/resources/lang/messages_zh_CN.properties
=> [BACKLOG-25043] Simplified Chinese localization

assemblies/pdi/pom.xml, core/impl/pom.xml, core/impl/src/main/java/pt/webdetails/cdf/dd/model/meta/reader/cdexml/XmlComponentTypeReader.java, core/impl/src/main/java/pt/webdetails/cdf/dd/model/meta/reader/cdexml/XmlPropertyTypeReader.java, core/impl/src/main/java/pt/webdetails/cdf/dd/model/meta/reader/cdexml/fs/XmlFsPluginModelReader.java, core/impl/src/main/java/pt/webdetails/cdf/dd/util/Utils.java, core/impl/src/test/java/pt/webdetails/cdf/dd/util/UtilsTestDom4J.java, pentaho/impl/pom.xml, pentaho/impl/src/main/java/pt/webdetails/cdf/dd/CdeSettings.java, pentaho/impl/src/test/java/pt/webdetails/cdf/dd/settings/CdfDDSettingsForTesting.java, pom.xml
This is one of a series of PRs. See pentaho/maven-parent-poms#70 for the complete list and more details. **Do not merge until further notice!**
@graimundo
=> [PPP-4182] Use of vulnerable component dom4j-1.6.1.jar  CVE-2018-1000632

webclient/impls/core/src/main/javascript/cdf-dd-wizardmanager.js
@pamval @duarteteixeira 
@ricardosilva88 @pentaho-lmartins 
@dcleao Can you take a look at this one?
=> [CDE-969] No datasource created using OLAP Chart Wizard

assemblies/pdi/pom.xml, core/impl/pom.xml, core/impl/src/main/java/pt/webdetails/cdf/dd/model/meta/reader/cdexml/XmlComponentTypeReader.java, core/impl/src/main/java/pt/webdetails/cdf/dd/model/meta/reader/cdexml/XmlPropertyTypeReader.java, core/impl/src/main/java/pt/webdetails/cdf/dd/model/meta/reader/cdexml/fs/XmlFsPluginModelReader.java, core/impl/src/main/java/pt/webdetails/cdf/dd/util/Utils.java, core/impl/src/test/java/pt/webdetails/cdf/dd/util/UtilsTestDom4J.java, pentaho/impl/pom.xml, pentaho/impl/src/main/java/pt/webdetails/cdf/dd/CdeSettings.java, pentaho/impl/src/test/java/pt/webdetails/cdf/dd/settings/CdfDDSettingsForTesting.java, pom.xml
Cherry-pick of #899 into 8.1 branch. Note that this one has two commits.
@ssamora @LeonardoCoelho71950
=> [SP-4687] Backport of PPP-4182 - Use of vulnerable component dom4j-1.6.1.jar  CVE-2018-1000632 (8.1 Suite)

assemblies/platform/pentaho-cdf-dd/src/main/resources/plugin.spring.xml, pentaho/impl/src/main/java/pt/webdetails/cdf/dd/api/DashboardsApi.java, pentaho/impl/src/main/java/pt/webdetails/cdf/dd/impl/DashboardsImpl.java
@tgf @plagoa @JoaoRPF and @marcoslarsen please review.
This branch is handy for dev environment... better to have it inside company remote
=> Add dashboard api to the normal CDE build

components/assemblies/cde-components-pdi/src/main/config/javascript/build.js, components/assemblies/cde-components-platform/src/main/config/javascript/build.js, package.json
@webdetails/millenniumfalcon @webdetails/x-wing please review
=> [BACKLOG-22832] Upgrade require.js and r.js to version 2.3.6

osgi/impl/pom.xml, pom.xml
=> [BACKLOG-27566] Centralize SLF4J dependency

core/impl/src/main/java/pt/webdetails/cdf/dd/CdeConstants.java, samples/src/main/resources/samples/karaf-dashboard/index.html
- Nedds: https://github.com/pentaho/pentaho-platform-plugin-common-ui/pull/1397
=> [BACKLOG-27098] Changing CDF's application id from "cdf" to "pentaho/cdf".

core/impl/src/main/java/pt/webdetails/cdf/dd/render/DependenciesManager.java, pentaho/impl/src/main/java/pt/webdetails/cdf/dd/CdeLifeCycleListener.java, pentaho/impl/src/main/java/pt/webdetails/cdf/dd/PentahoCdeEnvironment.java
The issue was not with legacy dashboards, but instead with loading and packaging of legacy custom components saved in the repository.
Merge after -> https://github.com/webdetails/cpf/pull/145
=> [CDE-1001] Legacy components are not being handled as expected

cde-pentaho5/src/pt/webdetails/cdf/dd/CdeLifeCycleListener.java
@davidmsantos90 please review
@smmribeiro @bantonio82 please merge. **Please note that this is not a cherry-pick.**
=> [SP-5101][CDE-1001] Legacy components are not being handled as expected

pentaho/impl/src/main/java/pt/webdetails/cdf/dd/CdeLifeCycleListener.java
Re-adding checked exceptions to the overriden methods
@bantonio82
=> [SP-5100] Fix: Re-adding checked exception

components/impls/core/src/main/javascript/components/NewMapComponent/amd/engines/openlayers2/MapEngineOpenLayers.js
@pentaho-lmartins @bantonio82 @ssamora @smmribeiro
=> [CDE-955] NewMapComponent - Can't set zoomlevels higher than 15

components/impls/core/src/main/javascript/components/NewMapComponent/amd/engines/google/MapEngineGoogle.js
Merge Masters:  @pentaho-lmartins and @smmribeiro
Cherry-picks:
* https://github.com/Webdetails/cde/commit/43fbea6639e4d359b18220b920c2aa8c0ac5c999
=> [SP-5316] Backport of CDE-1015 - Not able to build a Google Satellite with Google as engine (8.3 Suite)

pentaho/impl/pom.xml, pentaho/impl/src/main/java/pt/webdetails/cdf/dd/DashboardDesignerContentGenerator.java, pentaho/impl/src/main/java/pt/webdetails/cdf/dd/api/ResourcesApi.java, pentaho/impl/src/test/java/pt/webdetails/cdf/dd/DashboardDesignerContentGeneratorTest.java
**Attention: This is the outcome of an automated process!**
Merge Masters: @pentaho-lmartins and @smmribeiro
Cherry-picks:
* https://github.com/Webdetails/cde/commit/1b7e76e0093cc727f1d514c13e2b168d07c31bdf
=> [SP-5330] Backport of CDE-1021 - Not able to download the resources like JSON, PNG using REST API calling the XCDF file (8.3 Suite)

assemblies/platform/pentaho-cdf-dd/src/main/resources/css/sunny/jquery-ui-1.10.4.custom.css
**Attention: This is the outcome of an automated process!**
Merge Masters: @ppatricio and @bcostahitachivantara
Cherry-picks:
* https://github.com/Webdetails/cde/commit/076fd38813507b58f0899b8d18810f5926b55626
=> [SP-5351] Backport of CDE-1029 - CDE - Datasources Panel layout - XPATH Queries not selected (8.3 Suite)

assemblies/platform/pentaho-cdf-dd/src/main/resources/static/about.fancybox.html, assemblies/platform/pentaho-cdf-dd/src/main/resources/static/documentation.fancybox.html
=> [CDE-1016] CDE microsite link is not working

assemblies/platform/pentaho-cdf-dd-samples/src/main/resources/plugin-samples/pentaho-cdf-dd/legacy/tests/SiteMap/siteMap.cdfde, assemblies/platform/pentaho-cdf-dd-samples/src/main/resources/plugin-samples/pentaho-cdf-dd/tests/SiteMap/siteMap.cdfde, assemblies/platform/pentaho-cdf-dd/src/main/resources/static/about.fancybox.html, assemblies/platform/pentaho-cdf-dd/src/main/resources/static/documentation.fancybox.html, components/impls/core/src/test/javascript/cde/components/SiteMapComponent/amd/SiteMapComponent-spec.js
=> [CDE-1017] CDE links to Hitachi Vantara Community site are not working

assemblies/platform/pentaho-cdf-dd/src/main/resources/static/about.fancybox.html, assemblies/platform/pentaho-cdf-dd/src/main/resources/static/documentation.fancybox.html
@webdetails/millenniumfalcon @pentaho-lmartins (couldn't find the users @rmansoor and @pentaho-svigneri in webdetails). please review
=> [CDE-1016] New link for CDE community page

assemblies/platform/pentaho-cdf-dd/src/main/resources/css/documentation.fancybox.css, assemblies/platform/pentaho-cdf-dd/src/main/resources/static/documentation.fancybox.html, webclient/impls/core/src/main/javascript/cdf-dd.js
=> [BACKLOG-33071] Documentation pop up is not render correctly

components/impls/core/src/main/javascript/components/NewMapComponent/amd/engines/google/MapEngineGoogle.js, components/impls/core/src/test/javascript/cde/components/NewMapComponent/amd/engines/google/MapEngineGoogle-spec.js, components/impls/core/src/test/javascript/mocks/google-map-mock.js
@pentaho-lmartins 
@ssamora 
@ppatricio 
@smmribeiro
=> [CDE-1042] - Popup on the marker in NewMapComponent not working with engine as "google"

components/impls/core/src/main/javascript/components/NewMapComponent/amd/engines/google/MapEngineGoogle.js, components/impls/core/src/test/javascript/cde/components/NewMapComponent/amd/engines/google/MapEngineGoogle-spec.js, components/impls/core/src/test/javascript/mocks/google-map-mock.js
@pentaho-lmartins 
@ssamora 
@ppatricio 
@smmribeiro
=> [SP-5679] - Backport of CDE-1042 - Popup on the marker in NewMapComponent not working with engine as "google" (9.0 Suite)

assemblies/platform/pentaho-cdf-dd-samples/src/main/resources/plugin-samples/pentaho-cdf-dd/legacy/tests/SiteMap/siteMap.cdfde, assemblies/platform/pentaho-cdf-dd-samples/src/main/resources/plugin-samples/pentaho-cdf-dd/tests/SiteMap/siteMap.cdfde, assemblies/platform/pentaho-cdf-dd/src/main/resources/resources/styles/WDDocs.html, assemblies/platform/pentaho-cdf-dd/src/main/resources/resources/styles/WDDocsRequire.html, assemblies/platform/pentaho-cdf-dd/src/main/resources/static/about.fancybox.html, assemblies/platform/pentaho-cdf-dd/src/main/resources/static/documentation.fancybox.html, components/impls/core/src/test/javascript/cde/components/SiteMapComponent/amd/SiteMapComponent-spec.js, samples/src/main/resources/samples/karaf-dashboard/index.html
@rmansoor 
@smmribeiro @bcostahitachivantara
=> [CDE-1060] CDE links with a no longer existing URL

core/impl/src/main/java/pt/webdetails/cdf/dd/model/inst/writer/cdfrunjs/dashboard/amd/PentahoCdfRunJsDashboardWriteContext.java, core/impl/src/test/java/pt/webdetails/cdf/dd/model/inst/writer/cdfrunjs/dashboard/amd/PentahoCdfRunJsDashboardWriteContextTest.java
@ssamora 
@smmribeiro 
@bcostahitachivantara
=> [CDE-1052] RequireJS and ${solution:mypath/myfile} in html - image not displayed

components/impls/core/src/main/javascript/components/CggComponent/amd/CggComponent.js, components/impls/core/src/main/javascript/components/CggComponent/legacy/cgg-implementation.js, components/impls/core/src/main/javascript/components/PopupComponent/legacy/popup.js
See also: https://github.com/webdetails/cdf/pull/1127
@smmribeiro, @ssamora could you please review and merge?
=> [CDF-1041] Fix encoding of array query string parameters

core/impl/src/main/java/pt/webdetails/cdf/dd/render/CdaRenderer.java
@smmribeiro 
@renato-s 
@andreramos89
=> [BACKLOG-35396] - Fix integration tests for cde project to run in both Java 11 and Java 8

core/impl/pom.xml, core/impl/src/main/java/pt/webdetails/cdf/dd/model/inst/writer/cdfrunjs/dashboard/legacy/CdfRunJsDashboardWriter.java, core/impl/src/main/java/pt/webdetails/cdf/dd/render/layout/ResourceFileRender.java, core/impl/src/main/java/pt/webdetails/cdf/dd/render/layout/ResourceRender.java, pentaho/impl/src/main/java/pt/webdetails/cdf/dd/api/RenderApi.java, pom.xml
@webdetails/sp-branch-write please review and merge.
=> [SP-6095] Backport of PPP-4690 - XSS on pentaho-cdf-dd/api/renderer/render?root parameter

core/impl/pom.xml, core/impl/src/main/java/pt/webdetails/cdf/dd/model/inst/writer/cdfrunjs/dashboard/legacy/CdfRunJsDashboardWriter.java, core/impl/src/main/java/pt/webdetails/cdf/dd/render/layout/ResourceFileRender.java, core/impl/src/main/java/pt/webdetails/cdf/dd/render/layout/ResourceRender.java, pentaho/impl/src/main/java/pt/webdetails/cdf/dd/api/RenderApi.java, pom.xml
@webdetails/sp-branch-write please review and merge.
=> [SP-6094] Backport of PPP-4690 - XSS on pentaho-cdf-dd/api/renderer/render?root parameter

components/impls/core/src/main/javascript/components/CggComponent/amd/CggComponent.js, components/impls/core/src/main/javascript/components/CggComponent/legacy/cgg-implementation.js, components/impls/core/src/main/javascript/components/PopupComponent/legacy/popup.js
@webdetails/sp-branch-write please review and merge.
=> [SP-6098] Backport of CDF-1041 - Fix encoding of array query string parameters

components/impls/core/src/main/javascript/components/CggComponent/amd/CggComponent.js, components/impls/core/src/main/javascript/components/CggComponent/legacy/cgg-implementation.js, components/impls/core/src/main/javascript/components/PopupComponent/legacy/popup.js
@webdetails/sp-branch-write please review and merge.
=> [SP-6099] Backport of CDF-1041 - Fix encoding of array query string parameters

assemblies/platform/pentaho-cdf-dd/src/main/resources/settings.xml, core/impl/src/main/java/pt/webdetails/cdf/dd/CdeConstants.java, pentaho/impl/src/main/java/pt/webdetails/cdf/dd/api/SyncronizerApi.java, pentaho/impl/src/test/java/pt/webdetails/cdf/dd/api/SynchronizerApiTest.java
@smmribeiro 
@andreramos89 
@renato-s
=> [PPP-4798] - Stored Cross-Site Scripting in CDE Dashboards

assemblies/platform/pentaho-cdf-dd/src/main/resources/settings.xml, core/impl/src/main/java/pt/webdetails/cdf/dd/CdeConstants.java, pentaho/impl/src/main/java/pt/webdetails/cdf/dd/api/SyncronizerApi.java, pentaho/impl/src/test/java/pt/webdetails/cdf/dd/api/SynchronizerApiTest.java
@smmribeiro 
@andreramos89 
@renato-s
=> [SP-6243] - Backport of PPP-4798 - Stored Cross-Site Scripting in CDE Dashboards (9.3 Suite)

assemblies/platform/pentaho-cdf-dd-disabled/src/main/resources/settings.xml.disabled, assemblies/platform/pentaho-cdf-dd/src/main/resources/settings.xml, core/impl/src/main/java/pt/webdetails/cdf/dd/CdeConstants.java, pentaho/impl/src/main/java/pt/webdetails/cdf/dd/api/SyncronizerApi.java, pentaho/impl/src/test/java/pt/webdetails/cdf/dd/api/SynchronizerApiTest.java
@smmribeiro 
@bcostahitachivantara 
@renato-s
=> [SP-6244] - Backport of PPP-4798 - Stored Cross-Site Scripting in CDE Dashboards (9.4 Suite)

core/impl/pom.xml, pom.xml
=> Revert "[PPP-4864] Vulnerable Component: JDom"

assemblies/pdi/cde-plugin-pdi/pom.xml, assemblies/pdi/cde-plugin-pdi/src/main/feature/feature.xml
Original Commits:
- https://github.com/webdetails/cde/commit/13d02c1f2fb80cf0e7d933ee39258cfda95a694b
- https://github.com/webdetails/cde/commit/2f459b4cd977a2fce4f530691db549f23e890e7c
❗ This PR needs to be squash & merge, to be a single commit and use the message in the PR title ❗ 
Merge together with https://github.com/pentaho/pentaho-det-ee/pull/697
=> [SP-6688] Backport of PPP-5167 - End-of-Life: AngularJS 1.8.0  Pentaho Data Integration - Move DET into a addon or a kar file (10.2 Suite)

osgi/impl/pom.xml, osgi/impl/src/main/java/org/pentaho/ctools/cde/cache/impl/Cache.java, pentaho/impl/pom.xml, pentaho/impl/src/main/java/pt/webdetails/cdf/dd/cache/impl/Cache.java, pom.xml
[BACKLOG-41596]-Upgrading EhCache 2 to JCache and EhCache 3
[BACKLOG-41596]: https://hv-eng.atlassian.net/browse/BACKLOG-41596?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [BACKLOG-41596]-Upgrading EhCache 2 to JCache and EhCache 3

osgi/impl/pom.xml, osgi/impl/src/main/java/org/pentaho/ctools/cde/cache/impl/Cache.java, osgi/impl/src/main/resources/ehcache.xml, pentaho/impl/pom.xml, pentaho/impl/src/main/java/pt/webdetails/cdf/dd/cache/impl/Cache.java, pentaho/impl/src/test/java/pt/webdetails/cdf/dd/DashboardDesignerContentGeneratorTest.java, pentaho/impl/src/test/resources/ehcache.xml
[BACKLOG-43689]-fix broken test cases in cde repo
[BACKLOG-43689]: https://hv-eng.atlassian.net/browse/BACKLOG-43689?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [BACKLOG-43689]-fix broken test cases in cde repo

osgi/impl/pom.xml, pentaho/impl/pom.xml, pom.xml
[BACKLOG-43757]-Upgrading Tomcat and its Related Software's to latest version
[BACKLOG-43757]: https://hv-eng.atlassian.net/browse/BACKLOG-43757?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [BACKLOG-43757]-Upgrading Tomcat and its Related Software's to latest version

osgi/impl/pom.xml, pentaho/impl/pom.xml
[BACKLOG-43209]-OSGi Assembly Issues
[BACKLOG-43209]: https://hv-eng.atlassian.net/browse/BACKLOG-43209?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [BACKLOG-43209]-OSGi Assembly Issues

assemblies/cde-renderer/feature/pom.xml, assemblies/pdi/cde-plugin-pdi/pom.xml, pom.xml
[BACKLOG-43874]-Fix JDK21 test pipeline(test1) build failures
[BACKLOG-43874]: https://hv-eng.atlassian.net/browse/BACKLOG-43874?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [BACKLOG-43874]-Fix JDK21 test pipeline(test1) build failures

core/impl/src/main/java/pt/webdetails/cdf/dd/render/CdaRenderer.java
@smmribeiro @befc @miguelappleton
=> fix: add proper initialization to XML parser [PPP-5719]
