webdetails/cde

cde-core/resource/resources/custom/components/OlapSelector/OlapSelector.css
cde-core/resource/resources/custom/components/OlapSelector/OlapSelector.js
cde-core/resource/resources/custom/components/OlapSelector/OlapSelector.less
cde-core/resource/resources/custom/components/OlapSelector/OlapSelectorComponent.js
cde-pentaho5/solution/pentaho-cdf-dd/tests/OlapSelector/index.locale
cde-pentaho5/solution/pentaho-cdf-dd/tests/OlapSelector/index.xml
cde-pentaho5/solution/pentaho-cdf-dd/tests/OlapSelector/olapSelector.cdfde
cde-pentaho5/solution/pentaho-cdf-dd/tests/OlapSelector/olapSelector.wcdf

- Replaced split(".") with appropriate regular expression
- Added sample
- Fixed minor bug when trying to parse to JSON a parameter containing an empty string

[CDE-440] - Olap selector component's addPreSelectValues function fails to calculate depth when a qualifiedName contains the '.' char

---

cde-core/resource/js/cdf-dd-tablemanager.js
cde-core/src/pt/webdetails/cdf/dd/CdeConstants.java
cde-core/src/pt/webdetails/cdf/dd/DashboardManager.java
cde-core/src/pt/webdetails/cdf/dd/model/inst/writer/cdfrunjs/components/amd/CdfRunJsExpressionParameterComponentWriter.java
cde-core/src/pt/webdetails/cdf/dd/model/inst/writer/cdfrunjs/components/amd/CdfRunJsGenericComponentWriter.java
cde-core/src/pt/webdetails/cdf/dd/model/inst/writer/cdfrunjs/components/amd/CdfRunJsParameterComponentWriter.java
cde-core/src/pt/webdetails/cdf/dd/model/inst/writer/cdfrunjs/dashboard/CdfRunJsDashboardWriteContext.java
cde-core/src/pt/webdetails/cdf/dd/model/inst/writer/cdfrunjs/dashboard/CdfRunJsDashboardWriteOptions.java
cde-core/src/pt/webdetails/cdf/dd/model/inst/writer/cdfrunjs/dashboard/amd/CdfRunJsDashboardWriter.java
cde-core/src/pt/webdetails/cdf/dd/model/inst/writer/cdfrunjs/dashboard/legacy/CdfRunJsDashboardWriter.java
cde-core/src/pt/webdetails/cdf/dd/render/RenderLayout.java
cde-core/test-src/pt/webdetails/cdf/dd/model/inst/writer/cdfrunjs/components/amd/CdfRunJsGenericComponentWriterTest.java
cde-core/test-src/pt/webdetails/cdf/dd/model/inst/writer/cdfrunjs/components/amd/CdfRunJsParameterComponentWriterTest.java
cde-core/test-src/pt/webdetails/cdf/dd/model/inst/writer/cdfrunjs/dashboard/amd/CdfRunJsDashboardWriterTest.java
cde-pentaho5/solution/pentaho-cdf-dd/pentaho-cdf-dd-require/dashboard/dashboard_module.xcdf
cde-pentaho5/solution/pentaho-cdf-dd/pentaho-cdf-dd-require/dashboard/index.properties
cde-pentaho5/solution/pentaho-cdf-dd/pentaho-cdf-dd-require/dashboard/index.xml
cde-pentaho5/solution/pentaho-cdf-dd/pentaho-cdf-dd-require/dashboard/template.html
cde-pentaho5/src/pt/webdetails/cdf/dd/api/RenderApi.java

- added the endpoint getDashboard to retrieve an AMD module of a dashboard
- allow users to use the special wrapper ${h:} when editing an AMD dashboard
- added a sample that requests and renders the Raphael sample dashboard using require
- updated unit tests

[CDE-371] - Investigate how can we request a dashboard using require

---

cde-core/src/pt/webdetails/cdf/dd/model/core/writer/js/JsWriterAbstract.java

- Adding the line feed (LF) character after each script and link tag to improve readability and resemble legacy output

[CDE-379] - Keep GetHeaders and GetContent for legacy usages

---

cde-core/src/pt/webdetails/cdf/dd/model/inst/writer/cdfrunjs/components/amd/CdfRunJsExpressionParameterComponentWriter.java
cde-core/src/pt/webdetails/cdf/dd/model/inst/writer/cdfrunjs/components/amd/CdfRunJsGenericComponentWriter.java
cde-core/src/pt/webdetails/cdf/dd/model/inst/writer/cdfrunjs/components/amd/CdfRunJsParameterComponentWriter.java
cde-core/src/pt/webdetails/cdf/dd/model/inst/writer/cdfrunjs/dashboard/amd/CdfRunJsDashboardWriter.java
cde-core/test-src/pt/webdetails/cdf/dd/model/inst/writer/cdfrunjs/components/amd/CdfRunJsGenericComponentWriterTest.java
cde-core/test-src/pt/webdetails/cdf/dd/model/inst/writer/cdfrunjs/components/amd/CdfRunJsParameterComponentWriterTest.java
cde-core/test-src/pt/webdetails/cdf/dd/model/inst/writer/cdfrunjs/dashboard/amd/CdfRunJsDashboardWriterTest.java

- Added "dashboard" local var to be used to reference the current AMD dashboard module inside its "_processComponents" function
- Added "wcdfSettings" local var to the "_processComponents" function of each AMD dashboard module
- Updated unit tests accordingly

[CDE-373] - Review the DashboardWriter to output require dashboards

---

cde-core/src/pt/webdetails/cdf/dd/editor/DashboardEditor.java
cde-pentaho/build.xml
cde-pentaho/resource/resources/custom/components/ViewManager/dashboardViews.js

- removed Mustache.compile deprecated function usage in 4.x
- exclude AMD custom components from 4.x builds
- added legacy signature for static function DashboardEditor.getEditor

[CDE-371] - Add support for Require js in CDE

---

cde-core/resource/js/cdf-dd-layout.js
cde-core/resource/js/cdf-dd.js
cde-core/resource/resources/cdf-dd.html
cde-core/resource/resources/custom/properties/Bootstrap/property.xml
cde-core/resource/resources/ext-editor.html
cde-core/src/pt/webdetails/cdf/dd/render/layout/BootstrapColumnRender.java
cde-core/test-js/legacy/cdf-dd-tablemanager-spec.js
cde-core/test-src/pt/webdetails/cdf/dd/render/layout/BootstrapColumnRenderTest.java

- [CDF-531] Removed reference to jquery.ui.autobox from CDE
- [CDE-527] As a user, I want bootstrap layout elements without an assigned xs span value to fall back to col-xs-12
- [CDE-528] As a user, I want bootstrap layout rows to only allow bootstrap layout column elements as children
- [CDE-529] Opening component parameter popup does not block use of arrow keys to navigate properties
@pamval rebase done. please review

[CDF-531][CDE-527][CDE-528][CDE-529]

---

cde-core/resource/js/cde-core-require-js-cfg.js
cde-core/src/pt/webdetails/cdf/dd/CdeConstants.java
cde-core/src/pt/webdetails/cdf/dd/model/inst/writer/cdfrunjs/dashboard/CdfRunJsDashboardWriteContext.java
cde-core/src/pt/webdetails/cdf/dd/model/inst/writer/cdfrunjs/dashboard/amd/CdfRunJsDashboardWriter.java
cde-core/src/pt/webdetails/cdf/dd/model/inst/writer/cdfrunjs/dashboard/amd/PentahoCdfRunJsDashboardWriteContext.java
cde-core/src/pt/webdetails/cdf/dd/model/inst/writer/cdfrunjs/dashboard/legacy/PentahoCdfRunJsDashboardWriteContext.java
cde-core/test-src/pt/webdetails/cdf/dd/model/inst/writer/cdfrunjs/dashboard/amd/CdfRunJsDashboardWriterTest.java
cde-pentaho5/src/pt/webdetails/cdf/dd/PentahoCdeEnvironment.java
cde-pentaho5/test-src/pt/webdetails/cdf/dd/CdeEnvironmentForTests.java
cde-pentaho5/test-src/pt/webdetails/cdf/dd/model/inst/writer/cdfrunjs/components/legacy/CdfRunJsParameterComponentWriterTest.java
cde-pentaho5/test-src/pt/webdetails/cdf/dd/model/inst/writer/cdfrunjs/dashboard/amd/PentahoCdfRunJsDashboardWriteContextForTesting.java
cde-pentaho5/test-src/pt/webdetails/cdf/dd/model/inst/writer/cdfrunjs/dashboard/amd/PentahoCdfRunJsDashboardWriteContextTest.java
cde-pentaho5/test-src/pt/webdetails/cdf/dd/model/inst/writer/cdfrunjs/dashboard/legacy/PentahoCdfRunJsDashboardWriteContextForTesting.java
cde-pentaho5/test-src/pt/webdetails/cdf/dd/model/inst/writer/cdfrunjs/dashboard/legacy/PentahoCdfRunJsDashboardWriteContextTest.java

- changed CSS external resource loading, now using css! RequireJS loader plugin
- fixed JS external resource paths for embedded dashboards
- added cdo and Utils as default libs for dashboards required using the getDashboard endpoint, same as when rendered
- unit tests

[CDE-543] - CSS external resources should be included using the css! requireJS plugin

---

cde-core/resource/resources/custom/amd-components/Duplicate/DuplicateComponent.js
cde-core/resource/resources/custom/components/Duplicate/component.xml
cde-core/resource/resources/custom/components/Duplicate/duplicate.js
cde-pentaho5/solution/pentaho-cdf-dd/pentaho-cdf-dd-require/tests/DuplicateComponent/duplicateComponent.cdfde
cde-pentaho5/solution/pentaho-cdf-dd/tests/DuplicateComponent/duplicateComponent.cdfde

- fully duplicate 'Target HTML object'  content, instead of each component individually
- moved mandatory 'Target HTML object' property form Advanced properties window into the main properties window	- reviewed sample to better show off the component's functionality

[CDE-554] - DuplicateComponent fails to duplicate the target HTML element's content

---

cde-core/src/pt/webdetails/cdf/dd/CdeConstants.java
cde-core/src/pt/webdetails/cdf/dd/model/inst/writer/cdfrunjs/dashboard/amd/CdfRunJsDashboardWriter.java
cde-core/test-src/pt/webdetails/cdf/dd/model/inst/writer/cdfrunjs/dashboard/amd/CdfRunJsDashboardWriterTest.java

- Added def, pv and pvc as default CDE dashboard AMD modules
- updated unit test

[CDE-643] Add def, pv and pvc to the default AMD dependency list when rendering CDE dashboards

---

cde-core/resource/resources/custom/amd-components/NewMapComponent/NewMapComponent.js
cde-core/resource/resources/custom/components/NewMapComponent/NewMapComponent.js

This is mostly for convenience, but also avoids confusion and covers a corner usecase.
@pamval please review.

[CLEANUP] The "Shape Definition" property of the NewMapComponent should be optional when using shapeResolver addIns

---

cde-core/resource/js/cdf-dd-components-selectors.js
cde-core/resource/js/cdf-dd-tablemanager.js
cde-core/resource/js/cdf-dd-util.js
cde-core/resource/js/cdf-dd.js
cde-pentaho/resource/js/cdf-dd-base.js

- replace `eval()` with `JSON.parse()` in cdf-dd-util.js, cdf-dd-util.js, cdf-dd-base.js
- in ListenersRenderer, amend self-written `obj.toString()` to return well-formed representation
- also change `value` generating algorithm in cdf-dd-tablemanager.js to follow ECMA standard of JSON string representation
(adopted from 467bc718dbbbe498a6cd857494e88573ef393ddf)
@afrjorge, @pamval, review it please. This is a backport of https://github.com/webdetails/cde/pull/678

[SP-2547] - Backport of PPP-3455 - Dynamic code injection vulnerabilities found (5.4 Suite)

---

cde-pentaho5/ivy.xml

The fix is needed due to using java 1.8, and incompatibility of asm old version (is used by jersey) reading new java 1.8 features 
The following scope of repositories is upgraded(except webdetails): The list is sorted in the order of build team runs
https://github.com/pentaho/pentaho-reporting
https://github.com/pentaho/mondrian
https://github.com/pentaho/pentaho-kettle
https://github.com/pentaho/pentaho-mondrianschemaworkbench-plugins
https://github.com/pentaho/pentaho-platform
https://github.com/webdetails/cpf
https://github.com/pentaho/pentaho-metaverse
https://github.com/pentaho/pdi-platform-utils-plugin
https://github.com/pentaho/pentaho-data-profiling
https://github.com/pentaho/data-access
https://github.com/pentaho/big-data-plugin
https://github.com/pentaho/pentaho-data-refinery …

[BACKLOG-8388] - Upgrade Jersey to 1.19.1 across the suite for Java 8 compatibility

---

cde-core/build.properties

This is part of a set of pull requests for the spring 4 upgrade work:
https://github.com/pentaho/pentaho-platform/pull/3104
https://github.com/webdetails/cpf/pull/98
https://github.com/webdetails/cdf/pull/870
https://github.com/webdetails/cda/pull/209
https://github.com/webdetails/cde/pull/718
https://github.com/pentaho/data-access/pull/783
https://github.com/pentaho/pentaho-reporting/pull/828
https://github.com/pentaho/pentaho-platform-plugin-reporting/pull/436
https://github.com/pentaho/pentaho-platform-plugin-common-ui/pull/842
https://github.com/pentaho/marketplace/pull/115
https://github.com/pentaho/big-data-plugin/pull/739
https://github.com/pentaho/pentaho-platform-ee/pull/972
https://github.com/pentaho/pentaho-platform-plugin-interactive-reporting/pull/477 …

[BACKLOG-10623] upgrade Spring framework

---

cde-core/resource/js/cdf-dd.js
cde-pentaho5/src/pt/webdetails/cdf/dd/api/RenderApi.java

- Using the CleanRequire template when creating new dashboards in CDE since the default is now requirejs.
- Changing RenderApi /new endpoint to assume that a new dashboard is amd.

[BACKLOG-11532]

---

cde-pentaho5/ivy.xml
cde-pentaho5/src/pt/webdetails/cdf/dd/api/EditorApi.java
cde-pentaho5/src/pt/webdetails/cdf/dd/api/RenderApi.java
cde-pentaho5/src/pt/webdetails/cdf/dd/api/ResourcesApi.java
cde-pentaho5/src/pt/webdetails/cdf/dd/api/SyncronizerApi.java
cde-pentaho5/src/pt/webdetails/cdf/dd/api/XSSHelper.java
cde-pentaho5/test-src/pt/webdetails/cdf/dd/api/EditorApiTest.java
cde-pentaho5/test-src/pt/webdetails/cdf/dd/api/RenderApiTest.java
cde-pentaho5/test-src/pt/webdetails/cdf/dd/api/SynchronizerApiTest.java
cde-pentaho5/test-src/pt/webdetails/cdf/dd/api/XSSHelperTest.java

HTML and WILDCARD content-types are obviously affected, but not only them. I've learned that there is an attack wich can also affect other content types, so I've added escaping to few more endpoints. 
plus unit tests. One test is failing with a fix and without it locally, but seems to be OK in other PRs, so may be a local issue.

[CDF-964]-Reflected XSS prevention

---

cde-core/resource/resources/base/properties/cccColorMode.xml

@davidmsantos90, @carlosrusso, @nantunes please review.
Depends on: https://github.com/webdetails/ccc/pull/278.

[BACKLOG-15020] New CCC chart, Sunburst color mode, `level`.

---

cde-core/resource/resources/base/components/Checkbox.xml
cde-core/resource/resources/base/components/Select.xml
cde-core/resource/resources/base/components/SelectMulti.xml
cde-core/resource/resources/base/properties/UseFirstValue.xml

- renamed the component property that controls first value selection, from `defaultIfEmpty` to `useFirstValue`, to be consistent with dashboards and common-ui plugins across the platform
- made `useFirstValue` available in the CDE editor advanced properties panel for the respective CDF base components. Radio and MultiButton not included because they don’t seem to support the `false` value and always default to the first available value.

[PDB-1987] Check box filters with no default value set, display the first checkbox as selected

---

cde-core/resource/resources/base/components/Checkbox.xml
cde-core/resource/resources/base/components/Select.xml
cde-core/resource/resources/base/components/SelectMulti.xml
cde-core/resource/resources/base/properties/UseFirstValue.xml

- renamed the component property that controls first value selection, from `defaultIfEmpty` to `useFirstValue`, to be consistent with dashboards and common-ui plugins across the platform
- made `useFirstValue` available in the CDE editor advanced properties panel for the respective CDF base components. Radio and MultiButton not included because they don’t seem to support the `false` value and always default to the first available value.

[SP-3990][PDB-1987] Check box filters with no default value set, display the first checkbox as selected

---

cde-core/resource/resources/base/components/Checkbox.xml
cde-core/resource/resources/base/components/Select.xml
cde-core/resource/resources/base/components/SelectMulti.xml
cde-core/resource/resources/base/properties/UseFirstValue.xml

- renamed the component property that controls first value selection, from `defaultIfEmpty` to `useFirstValue`, to be consistent with dashboards and common-ui plugins across the platform
- made `useFirstValue` available in the CDE editor advanced properties panel for the respective CDF base components. Radio and MultiButton not included because they don’t seem to support the `false` value and always default to the first available value.

[SP-3980][PDB-1987] Check box filters with no default value set, display the first checkbox as selected

---

assemblies/platform/pentaho-cdf-dd/src/assembly/assembly.xml
components/amd/assemblies/cde-components-amd-platform/pom.xml
components/amd/assemblies/cde-components-amd-platform/src/assembly/assembly.xml

@diogofscmariano @hbfernandes  @pamval please review.
Although we have a global requireJS config file, for legacy reasons, the plugin.xml cannot be changed so we still need to include the individual files in the built artifacts.

[BACKLOG-20079] Include individual RequireJS config files in the build artifacts for pentaho platform

---

assemblies/platform/pentaho-cdf-dd-disabled/src/main/resources/plugin.xml.disabled
assemblies/platform/pentaho-cdf-dd-disabled/src/main/resources/settings.xml.disabled
assemblies/platform/pentaho-cdf-dd/src/assembly/assembly.xml
assemblies/platform/pentaho-cdf-dd/src/main/resources/plugin.xml
components/amd/assemblies/cde-components-amd-platform/src/assembly/assembly.xml

- sync Pentaho Platform CE and EE configuration files (plugin.xml and settings.xml)
- use the same global CDE requireJS configuration file in both CE and EE Pentaho Server assemblies

[BACKLOG-20079] Mavenize the CDE plugin

---

webclient/impls/core/src/test/javascript/cdf-dd-components-others-spec.js

[BACKLOG-20970] - Choose from a list of available dataservice names when creating a dataservice datasource in CDE

---

components/impls/pentaho/src/main/javascript/components/NewMapComponent/amd/Map.ext.js

- The path changed when the PDI assembly was created for CDE

[BACKLOG-23027] MapComponent sample has broken images for markers

---

assemblies/platform/pentaho-cdf-dd/src/main/resources/resources/cdf-dd-default.html
assemblies/platform/pentaho-cdf-dd/src/main/resources/resources/cdf-dd.html

Removed Webdetails' logo from the CDE Editor.

[BACKLOG-25914] - Webdetails logo is still used in CDE editor

---

assemblies/cde-renderer/feature/src/main/feature/feature.xml
assemblies/cde-renderer/karaf/pom.xml
osgi/impl/pom.xml
pom.xml

[BACKLOG-27567] Remove unneeded org.osgi dependency
[BACKLOG-27565] Centralize CXF version
[BACKLOG-27577] Centralize karaf dependencies management
[BACKLOG-27578] Use parent pom centralized profile for feature generation
@graimundo

[BACKLOG-27567] Remove unneeded org.osgi dependency

---

components/impls/core/src/main/javascript/components/NewMapComponent/amd/engines/openlayers2/MapEngineOpenLayers.js

Max zoom level is 19. But there are 20 zoom levels, since 0 also counts.
@pentaho-lmartins @ssamora

[CDE-955] NewMapComponent - Can't set zoomlevels higher than 15

---

assemblies/pdi/pom.xml
pom.xml

Linked with this: pentaho/maven-parent-poms#163

[BACKLOG-30893] Centralize commons-logging in parent pom

---

components/impls/core/src/main/javascript/components/NewMapComponent/amd/engines/google/MapEngineGoogle.js

When the viewport is updated, it's being pinned to a hard-coded coordinate.
@pentaho-lmartins @ssamora 
@carlosrusso

[CDE-1013] Wrong plot when creating a map using Google engine

---

components/impls/core/src/main/javascript/components/NewMapComponent/amd/engines/google/MapEngineGoogle.js

Map skin wasn't being applied for Google's tileset.
@pentaho-lmartins @carlosrusso

[CDE-1015] Not able to build a Google Satellite with Google as engine

---

components/impls/core/src/main/javascript/components/NewMapComponent/amd/engines/google/MapEngineGoogle.js
components/impls/core/src/main/javascript/components/NewMapComponent/amd/engines/openlayers2/MapEngineOpenLayers.js

Merge Masters: @pentaho-lmartins and @smmribeiro
Cherry-picks:
* https://github.com/Webdetails/cde/commit/d11f2ca266c396616cc128bfde2d03ccfbca30e7

[SP-5327] Backport of CDE-1024 - Not define Default zoom level with Google as engine Map is not displayed (8.3 Suite)

---

assemblies/platform/pentaho-cdf-dd/src/main/resources/css/sunny/jquery-ui-1.10.4.custom.css

with the update of JQuery in PPP-4008, JQuery-UI was also updated to version 1.12.1. 
Since we have custom CSS files based on JQuery-UI 1.10.4 (that were already tweeked) we need to re-adapt to the new version.
@pentaho-lmartins

[CDE-1029] CDE - Datasources Panel layout - XPATH Queries not selected

---

assemblies/pdi/cde-plugin-pdi/pom.xml

bundles not marked as dependency will be added into the kar file repository to make sure they are installed when the kar is deployed
@pentaho/millenniumfalcon @graimundo please review

feat: include transitive dependencies in DET-EE kar [PPP-5167]

---

assemblies/cde-renderer/karaf/src/main/resources/etc/org.ops4j.pax.web.cfg
assemblies/cde-renderer/solr/pom.xml
assemblies/cde-renderer/solr/src/main/resources/OSGI-INF/blueprint/blueprint.xml
assemblies/pdi/pom.xml
foundry-extensions/impl/pom.xml
foundry-extensions/impl/src/main/java/org/pentaho/ctools/cde/api/DashboardsApi.java
osgi/impl/pom.xml
osgi/impl/src/main/java/org/pentaho/ctools/cde/api/RenderApi.java
osgi/impl/src/main/java/org/pentaho/ctools/cde/api/ResourcesApi.java
osgi/impl/src/test/java/org/pentaho/ctools/cde/api/RenderApiTest.java
osgi/impl/src/test/java/org/pentaho/ctools/cde/api/ResourcesApiTest.java
pentaho/impl/pom.xml
pentaho/impl/src/main/java/pt/webdetails/cdf/dd/DashboardDesignerContentGenerator.java
pentaho/impl/src/main/java/pt/webdetails/cdf/dd/api/DatasourcesApi.java
pentaho/impl/src/main/java/pt/webdetails/cdf/dd/api/EditorApi.java
pentaho/impl/src/main/java/pt/webdetails/cdf/dd/api/PluginsApi.java
pentaho/impl/src/main/java/pt/webdetails/cdf/dd/api/RenderApi.java
pentaho/impl/src/main/java/pt/webdetails/cdf/dd/api/ResourcesApi.java
pentaho/impl/src/main/java/pt/webdetails/cdf/dd/api/SyncronizerApi.java
pentaho/impl/src/main/java/pt/webdetails/cdf/dd/api/VersionApi.java
pentaho/impl/src/test/java/pt/webdetails/cdf/dd/DashboardDesignerContentGeneratorTest.java
pentaho/impl/src/test/java/pt/webdetails/cdf/dd/api/RenderApiForTesting.java
pentaho/impl/src/test/java/pt/webdetails/cdf/dd/api/RenderApiTest.java
pentaho/impl/src/test/java/pt/webdetails/cdf/dd/api/ResourcesApiTest.java
pentaho/impl/src/test/java/pt/webdetails/cdf/dd/api/SynchronizerApiTest.java
pom.xml

[BACKLOG-41287]-Upgrading cde from Java-ee to Jakarta-ee support with Tomcat-10.X
[BACKLOG-41287]: https://hv-eng.atlassian.net/browse/BACKLOG-41287?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[BACKLOG-41287]-Upgrading cde from Java-ee to Jakarta-ee support with Tomcat-10.X

---

assemblies/cde-renderer/solr/pom.xml

[BACKLOG-42885]-Upgrading Jetty version from 11.0.14 to 12.0.15 to support Jakarta EE 10
[BACKLOG-42885]: https://hv-eng.atlassian.net/browse/BACKLOG-42885?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[BACKLOG-42885]-Upgrading Jetty version from 11.0.14 to 12.0.15 to support Jakarta EE 10

---

assemblies/pdi/cde-plugin-pdi/src/main/feature/feature.xml

this will fix DET kar installation that was failing due to this missing dependency
cc: @angel-ramoscardona @eddie-martinez

fix: restore jdom dependencyin CDE feature [PPP-5167]
